### ISSUE TITLE
Invoice Number Changes when Editing Customer

### ISSUE THREAD

**Issue by Bipedal** [InvoiceShelf/InvoiceShelf#101]
**Describe the bug**
If an existing invoice is edited, when the customer is changed (by clicking Deselect, then picking a new one from the search/dropdown), the invoice number resets as if a new invoice were being created.

**Expected behavior**
When editing an existing invoice, I'd expect the number to remain unless I manually changed it.

**Please complete the following information:**
- InvoiceShelf version: 1.2.2
- PHP version: 8.2.18
- Database type and version: mariadb:10

**Optional info**
- OS:  Debian 12 (Docker Compose)
- Browser: Firefox, Chrome

**Comment by mchev** [comment]
Hello @Bipedal , I can't reproduce the error. When changing customer in the edition of an existing invoice (sent or not) the invoice number remains the same.

Is it possible to have more information on the billing configuration? /admin/settings/customization #invoices
Was the installation particular, db modified manually, migration from crater?

**Comment by Bipedal** [comment]
I've previously modified the highest invoice number in order to have new ones counting from there instead of an already-used one.

Sorry, but I'm not sure where to find that directory. I'm happy to provide as much info as I can, but I might need a little bit of handholding, if that's alright with you. So far I've got a shell into my invoiceshelf docker instance, starting at /var/www/html/InvoiceShelf.

**Comment by mchev** [comment]
> I've previously modified the highest invoice number in the database in order to have new ones counting from there instead of an already-used one.

I see, so if you updated the `invoice_number` manually in the db you should also update the `sequence_number` field because numbers are generated from there.

**Comment by Bipedal** [comment]
So it looks like it was sequence_number that I adjusted. Previously, the highest was 57, now it's 88. Is it the ID that I should update?

Sorry, I realize this isn't necessarily applicable to anyone else, I didn't mean for it to turn into private tech support.
![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/7750652/29eeefff-2d6e-437e-a039-204f1d06b271)

**Comment by mchev** [comment]
Do not touch the ID.

It seems that the system will always try to take the biggest existing `sequence_number` and increment it by 1 each time. So if you modify it and there are already larger ones recorded, it will start again from the largest.

Either manually check that all `sequence_number`s are correct and put them back in order, or let the natural order continue.

Either way, it's not really a bug. I'll let you continue the conversation on the discord where you can find all the help you need.

Here is the code :

```php
        $last = $this->model::orderBy('sequence_number', 'desc')
            ->where('company_id', $companyId)
            ->where('sequence_number', '<>', null)
            ->take(1)
            ->first();

        $this->nextSequenceNumber = ($last) ? $last->sequence_number + 1 : 1;
```
