### ISSUE TITLE
Quantity Requiring Integer

### ISSUE THREAD

**Issue by clockwiseq** [InvoiceShelf/InvoiceShelf#105]
**Describe the bug**
Item Quantity on an invoice is requiring an integer and not a float/decimal.

**Expected behavior**
A float/decimal should be able to be entered/saved in the quantity field of an item since the unit can be custom like Hour or something with a precision measure such as weights.

**Screenshots**
![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/6662538/c6b96a2e-1b39-49bc-b922-68221becfbb0)

**Please complete the following information:**
- InvoiceShelf version: 1.2.2
- PHP version: 8.2
- Database type and version: MySQL (latest version)

**Optional info**
- OS:  Ubuntu
- Browser: Edge, Chrome, & Firefox

**Comment by gdarko** [comment]
Hey @clockwiseq  - This issue will be solved in the next release. Already closed in #80
