### ISSUE TITLE
Reports: PDF Filename Labels

### ISSUE THREAD

**Issue by Bipedal** [InvoiceShelf/InvoiceShelf#106]
**Is your feature request related to a problem? Please describe.**
When I generate PDF reports and save them either through Invoiceshelf's "Download PDF" button, or the toolbar within the browser's PDF viewer frame, the generated report is always titled "document.pdf," which isn't very descriptive, especially when I'm making a few different reports (I haven't done my taxes in like 4 years, so I'm catching up now).

**Describe the solution you'd like**
If it's possible, I'd like see the PDFs receive descriptive names by default. Ideally, the information specified in the generator tab would be used: "Report-Sales by Customer (2023-12-01_2024-06-30).pdf", "Report-Profit Loss (2022-01-01_2023-12-31).pdf", or whatever.

**Describe alternatives you've considered**
At minimum, reports generated from the "Sales" tab could be called "Report-Sales.pdf", and From Profit & Loss "Report-Profit and Loss.pdf". Maybe even give them incrementing numbers each generation, so at least when I'm generating a few of them, I don't have to rename each one: "Report-Sales0001.pdf" "Report-Sales0002.pdf" and so on until it loops at 9999.

**Comment by rihards-simanovics** [comment]
linked to #252
