### ISSUE TITLE
Errors in Model Name Migration from CRATER

### ISSUE THREAD

**Issue by jmsx** [InvoiceShelf/InvoiceShelf#107]
#### Description

We have identified a problem during the migration from CRATER where model names in some tables, such as `emaillogs`, are not updated correctly. Specifically, the `mailable_type` column retains the string `crater`, causing data errors. This same issue is found in custom fields (`custom_fields`).

#### Steps to Reproduce

1. Migrate data from CRATER to the new database.
2. Check the `emaillogs` table and observe that the `mailable_type` column contains the value `crater` instead of the correct model name.
3. Check the custom fields (`custom_fields`) and verify that the model names also contain incorrect values.

#### Expected Behavior

The values in the `mailable_type` column and in the custom fields should be correctly updated during migration to reflect the appropriate model names in the new system.

#### Actual Behavior

The values in the `mailable_type` column of the `emaillogs` table and in the custom fields (`custom_fields`) retain the string `crater`, causing inconsistencies and data errors.

#### Impact

This issue can cause errors in applications that rely on this data, as the incorrect names can lead to failures in application logic and data integrity.

#### Possible Solution

Implement a migration script that correctly updates the values of the affected columns:
- Update the values in the `mailable_type` column in the `emaillogs` table.
- Correct the model names in the custom fields (`custom_fields`).

#### Additional Notes

- This issue was detected during migration testing.
- It is recommended to perform post-migration validation to ensure data integrity.

**Comment by gdarko** [comment]
This can be closed now :-)

**Comment by jmsx** [comment]
Great job! :)
