### ISSUE TITLE
Creating invoice wont show company logo

### ISSUE THREAD

**Issue by hari-bo** [InvoiceShelf/InvoiceShelf#119]
**Describe the bug**
Within settings - company info - added logo in png format

**Expected behavior**
When creating invoice the company logo is added.

**Screenshots**
![Screenshot from 2024-07-16 20-30-08](https://github.com/user-attachments/assets/cf41c8cd-cb01-4752-8dc2-48ce030ffce6)

**Please complete the following information:**
- InvoiceShelf version: 1.3.0 docker 
- PHP version: 8.2.0
- Database type and version: MariaDB 10.11.8

**Optional info**
- OS:  Ubuntu 22.04.4 LTS

- Browser: [e.g. chrome, safari]
- Firefox 127

**Comment by vehbiu** [comment]
@hari-bo How was this fixed?

**Comment by hari-bo** [comment]
> @hari-bo How was this fixed?

Not, but i have moved to solidinvoice. The basic functionality is not good at the moment for this project.

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
