### ISSUE TITLE
Unable to login after migration

### ISSUE THREAD

**Issue by razarahil** [InvoiceShelf/InvoiceShelf#120]
**Describe the bug**
Unable to login, on console, I'm getting following error

main-q-Vi2wV1.js:2 
 GET https://example.com/sanctum/csrf-cookie 404 (Not Found)

example.com/:1 Uncaught (in promise) 
Hl {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}

**Please complete the following information:**
- InvoiceShelf version: 1.3.0
- PHP version: 8.3
- Database type and version: mariadb 

**Optional info**
- OS:  ubuntu 22.04

**Comment by mchev** [comment]
Hi @razarahil, is your .env correctly set ?

```env
SANCTUM_STATEFUL_DOMAINS="your-domain.tld"
SESSION_DOMAIN="your-domain.tld"
```

https://github.com/InvoiceShelf/docker/issues/16#issuecomment-2226689300

**Comment by razarahil** [comment]
@mchev yes,  without any http or https as per the document.

**Comment by gdarko** [comment]
Hey @razarahil  - Can you do and forward the output:

```
php artisan route:list
```

Also, are you using docker or you selfhost the app without docker?

If not using docker: 

- which web server you are running on your local configuration?
- it's possible that you don't have rewrite rules enabled

**Comment by razarahil** [comment]
` GET|HEAD        / ................................................................................................................................................................................... home
  GET|HEAD        admin/{vue?} ............................................................................................................................................................. admin.dashboard
  GET|HEAD        api/cron .................................................................................................................................................... V1\Webhook\CronJobController
  GET|HEAD        api/ping ............................................................................................................................................................................ ping
  GET|HEAD        api/v1/abilities ....................................................................................................................................... V1\Admin\Role\AbilitiesController
  GET|HEAD        api/v1/app/version .................................................................................................................................................. AppVersionController
  GET|HEAD        api/v1/auth/check ................................................................................................................................... V1\Admin\Mobile\AuthController@check
  POST            api/v1/auth/login ................................................................................................................................... V1\Admin\Mobile\AuthController@login
  POST            api/v1/auth/logout ................................................................................................................................. V1\Admin\Mobile\AuthController@logout
  POST            api/v1/auth/password/email ..................................................................................................... V1\Admin\Auth\ForgotPasswordController@sendResetLinkEmail
  POST            api/v1/auth/reset/password ................................................................................................................... V1\Admin\Auth\ResetPasswordController@reset
  GET|HEAD        api/v1/backups ................................................................................................................... backups.index › V1\Admin\Backup\BackupsController@index
  POST            api/v1/backups ................................................................................................................... backups.store › V1\Admin\Backup\BackupsController@store
  GET|HEAD        api/v1/backups/{backup} ............................................................................................................ backups.show › V1\Admin\Backup\BackupsController@show
  PUT|PATCH       api/v1/backups/{backup} ........................................................................................................ backups.update › V1\Admin\Backup\BackupsController@update
  DELETE          api/v1/backups/{backup} ...................................................................................................... backups.destroy › V1\Admin\Backup\BackupsController@destroy
  GET|HEAD        api/v1/bootstrap .................................................................................................................................... V1\Admin\General\BootstrapController
  GET|HEAD        api/v1/categories .................................................................................................. categories.index › V1\Admin\Expense\ExpenseCategoriesController@index
  POST            api/v1/categories .................................................................................................. categories.store › V1\Admin\Expense\ExpenseCategoriesController@store
  GET|HEAD        api/v1/categories/{category} ......................................................................................... categories.show › V1\Admin\Expense\ExpenseCategoriesController@show
  PUT|PATCH       api/v1/categories/{category} ..................................................................................... categories.update › V1\Admin\Expense\ExpenseCategoriesController@update
  DELETE          api/v1/categories/{category} ................................................................................... categories.destroy › V1\Admin\Expense\ExpenseCategoriesController@destroy
  GET|HEAD        api/v1/check/update ............................................................................................................................... V1\Admin\Update\CheckVersionController
  POST            api/v1/companies .............................................................................................................................. V1\Admin\Company\CompaniesController@store
  GET|HEAD        api/v1/companies ................................................................................................................... V1\Admin\Company\CompaniesController@getUserCompanies
  POST            api/v1/companies/delete ..................................................................................................................... V1\Admin\Company\CompaniesController@destroy
  PUT             api/v1/company ......................................................................................................................... V1\Admin\Settings\CompanyController@updateCompany
  GET|HEAD        api/v1/company/has-transactions ............................................................................................. V1\Admin\Settings\CompanyCurrencyCheckTransactionsController
  GET|HEAD        api/v1/company/mail/config ....................................................................................................... V1\Admin\Settings\GetCompanyMailConfigurationController
  GET|HEAD        api/v1/company/settings ................................................................................................................... V1\Admin\Settings\GetCompanySettingsController
  POST            api/v1/company/settings ................................................................................................................ V1\Admin\Settings\UpdateCompanySettingsController
  POST            api/v1/company/upload-logo ......................................................................................................... V1\Admin\Settings\CompanyController@uploadCompanyLogo
  GET|HEAD        api/v1/config .......................................................................................................................................... V1\Admin\General\ConfigController
  GET|HEAD        api/v1/countries .................................................................................................................................... V1\Admin\General\CountriesController
  GET|HEAD        api/v1/currencies .................................................................................................................................. V1\Admin\General\CurrenciesController
  POST            api/v1/currencies/bulk-update-exchange-rate .................................................................................................. V1\Admin\General\BulkExchangeRateController
  GET|HEAD        api/v1/currencies/used ................................................................................................................... V1\Admin\General\GetAllUsedCurrenciesController
  GET|HEAD        api/v1/currencies/{currency}/active-provider ........................................................................................... V1\Admin\ExchangeRate\GetActiveProviderController
  GET|HEAD        api/v1/currencies/{currency}/exchange-rate ............................................................................................... V1\Admin\ExchangeRate\GetExchangeRateController
  GET|HEAD        api/v1/current-company ................................................................................................................................ V1\Admin\Company\CompanyController
  GET|HEAD        api/v1/custom-fields ............................................................................................. custom-fields.index › V1\Admin\CustomField\CustomFieldsController@index
  POST            api/v1/custom-fields ............................................................................................. custom-fields.store › V1\Admin\CustomField\CustomFieldsController@store
  GET|HEAD        api/v1/custom-fields/create .................................................................................... custom-fields.create › V1\Admin\CustomField\CustomFieldsController@create
  GET|HEAD        api/v1/custom-fields/{custom_field} ................................................................................ custom-fields.show › V1\Admin\CustomField\CustomFieldsController@show
  PUT|PATCH       api/v1/custom-fields/{custom_field} ............................................................................ custom-fields.update › V1\Admin\CustomField\CustomFieldsController@update
  DELETE          api/v1/custom-fields/{custom_field} .......................................................................... custom-fields.destroy › V1\Admin\CustomField\CustomFieldsController@destroy
  GET|HEAD        api/v1/custom-fields/{custom_field}/edit ........................................................................... custom-fields.edit › V1\Admin\CustomField\CustomFieldsController@edit
  GET|HEAD        api/v1/customers ........................................................................................................... customers.index › V1\Admin\Customer\CustomersController@index
  POST            api/v1/customers ........................................................................................................... customers.store › V1\Admin\Customer\CustomersController@store
  GET|HEAD        api/v1/customers/create .................................................................................................. customers.create › V1\Admin\Customer\CustomersController@create
  POST            api/v1/customers/delete ..................................................................................................................... V1\Admin\Customer\CustomersController@delete
  GET|HEAD        api/v1/customers/{customer} .................................................................................................. customers.show › V1\Admin\Customer\CustomersController@show
  PUT|PATCH       api/v1/customers/{customer} .............................................................................................. customers.update › V1\Admin\Customer\CustomersController@update
  DELETE          api/v1/customers/{customer} ............................................................................................ customers.destroy › V1\Admin\Customer\CustomersController@destroy
  GET|HEAD        api/v1/customers/{customer}/edit ............................................................................................. customers.edit › V1\Admin\Customer\CustomersController@edit
  GET|HEAD        api/v1/customers/{customer}/stats .............................................................................................................. V1\Admin\Customer\CustomerStatsController
  GET|HEAD        api/v1/dashboard .................................................................................................................................. V1\Admin\Dashboard\DashboardController
  GET|HEAD        api/v1/date/formats ............................................................................................................................... V1\Admin\General\DateFormatsController
  GET|HEAD        api/v1/disk/drivers ...................................................................................................................... V1\Admin\Settings\DiskController@getDiskDrivers
  GET|HEAD        api/v1/disks ........................................................................................................................ disks.index › V1\Admin\Settings\DiskController@index
  POST            api/v1/disks ........................................................................................................................ disks.store › V1\Admin\Settings\DiskController@store
  GET|HEAD        api/v1/disks/{disk} ................................................................................................................... disks.show › V1\Admin\Settings\DiskController@show
  PUT|PATCH       api/v1/disks/{disk} ............................................................................................................... disks.update › V1\Admin\Settings\DiskController@update
  DELETE          api/v1/disks/{disk} ............................................................................................................. disks.destroy › V1\Admin\Settings\DiskController@destroy
  GET|HEAD        api/v1/download-backup .......................................................................................................................... V1\Admin\Backup\DownloadBackupController
  GET|HEAD        api/v1/estimates ........................................................................................................... estimates.index › V1\Admin\Estimate\EstimatesController@index
  POST            api/v1/estimates ........................................................................................................... estimates.store › V1\Admin\Estimate\EstimatesController@store
  POST            api/v1/estimates/delete ..................................................................................................................... V1\Admin\Estimate\EstimatesController@delete
  GET|HEAD        api/v1/estimates/templates ................................................................................................................. V1\Admin\Estimate\EstimateTemplatesController
  GET|HEAD        api/v1/estimates/{estimate} .................................................................................................. estimates.show › V1\Admin\Estimate\EstimatesController@show
  PUT|PATCH       api/v1/estimates/{estimate} .............................................................................................. estimates.update › V1\Admin\Estimate\EstimatesController@update
  DELETE          api/v1/estimates/{estimate} ............................................................................................ estimates.destroy › V1\Admin\Estimate\EstimatesController@destroy
  POST            api/v1/estimates/{estimate}/convert-to-invoice ............................................................................................... V1\Admin\Estimate\ConvertEstimateController
  POST            api/v1/estimates/{estimate}/send ................................................................................................................ V1\Admin\Estimate\SendEstimateController
  GET|HEAD        api/v1/estimates/{estimate}/send/preview ................................................................................................. V1\Admin\Estimate\SendEstimatePreviewController
  POST            api/v1/estimates/{estimate}/status ...................................................................................................... V1\Admin\Estimate\ChangeEstimateStatusController
  GET|HEAD        api/v1/exchange-rate-providers ................................................................ exchange-rate-providers.index › V1\Admin\ExchangeRate\ExchangeRateProviderController@index
  POST            api/v1/exchange-rate-providers ................................................................ exchange-rate-providers.store › V1\Admin\ExchangeRate\ExchangeRateProviderController@store
  GET|HEAD        api/v1/exchange-rate-providers/{exchange_rate_provider} ......................................... exchange-rate-providers.show › V1\Admin\ExchangeRate\ExchangeRateProviderController@show
  PUT|PATCH       api/v1/exchange-rate-providers/{exchange_rate_provider} ..................................... exchange-rate-providers.update › V1\Admin\ExchangeRate\ExchangeRateProviderController@update
  DELETE          api/v1/exchange-rate-providers/{exchange_rate_provider} ................................... exchange-rate-providers.destroy › V1\Admin\ExchangeRate\ExchangeRateProviderController@destroy
  GET|HEAD        api/v1/expenses ............................................................................................................... expenses.index › V1\Admin\Expense\ExpensesController@index
  POST            api/v1/expenses ............................................................................................................... expenses.store › V1\Admin\Expense\ExpensesController@store
  POST            api/v1/expenses/delete ........................................................................................................................ V1\Admin\Expense\ExpensesController@delete
  GET|HEAD        api/v1/expenses/{expense} ....................................................................................................... expenses.show › V1\Admin\Expense\ExpensesController@show
  PUT|PATCH       api/v1/expenses/{expense} ................................................................................................... expenses.update › V1\Admin\Expense\ExpensesController@update
  DELETE          api/v1/expenses/{expense} ................................................................................................. expenses.destroy › V1\Admin\Expense\ExpensesController@destroy
  GET|HEAD        api/v1/expenses/{expense}/show/receipt ............................................................................................................ V1\Admin\Expense\ShowReceiptController
  POST            api/v1/expenses/{expense}/upload/receipts ....................................................................................................... V1\Admin\Expense\UploadReceiptController
  POST            api/v1/installation/database/config .............................................................................. V1\Installation\DatabaseConfigurationController@saveDatabaseEnvironment
  GET|HEAD        api/v1/installation/database/config ............................................................................... V1\Installation\DatabaseConfigurationController@getDatabaseEnvironment
  POST            api/v1/installation/finish .............................................................................................................................. V1\Installation\FinishController
  POST            api/v1/installation/login ................................................................................................................................ V1\Installation\LoginController
  GET|HEAD        api/v1/installation/permissions .................................................................................................... V1\Installation\FilePermissionsController@permissions
  GET|HEAD        api/v1/installation/requirements ..................................................................................................... V1\Installation\RequirementsController@requirements
  PUT             api/v1/installation/set-domain ....................................................................................................................... V1\Installation\AppDomainController
  GET|HEAD        api/v1/installation/wizard-step ....................................................................................................... V1\Installation\OnboardingWizardController@getStep
  POST            api/v1/installation/wizard-step .................................................................................................... V1\Installation\OnboardingWizardController@updateStep
  GET|HEAD        api/v1/invoices ............................................................................................................... invoices.index › V1\Admin\Invoice\InvoicesController@index
  POST            api/v1/invoices ............................................................................................................... invoices.store › V1\Admin\Invoice\InvoicesController@store
  POST            api/v1/invoices/delete ........................................................................................................................ V1\Admin\Invoice\InvoicesController@delete
  GET|HEAD        api/v1/invoices/templates .................................................................................................................... V1\Admin\Invoice\InvoiceTemplatesController
  GET|HEAD        api/v1/invoices/{invoice} ....................................................................................................... invoices.show › V1\Admin\Invoice\InvoicesController@show
  PUT|PATCH       api/v1/invoices/{invoice} ................................................................................................... invoices.update › V1\Admin\Invoice\InvoicesController@update
  DELETE          api/v1/invoices/{invoice} ................................................................................................. invoices.destroy › V1\Admin\Invoice\InvoicesController@destroy
  POST            api/v1/invoices/{invoice}/clone .................................................................................................................. V1\Admin\Invoice\CloneInvoiceController
  POST            api/v1/invoices/{invoice}/send .................................................................................................................... V1\Admin\Invoice\SendInvoiceController
  GET|HEAD        api/v1/invoices/{invoice}/send/preview ..................................................................................................... V1\Admin\Invoice\SendInvoicePreviewController
  POST            api/v1/invoices/{invoice}/status .......................................................................................................... V1\Admin\Invoice\ChangeInvoiceStatusController
  GET|HEAD        api/v1/items ........................................................................................................................... items.index › V1\Admin\Item\ItemsController@index
  POST            api/v1/items ........................................................................................................................... items.store › V1\Admin\Item\ItemsController@store
  GET|HEAD        api/v1/items/create .................................................................................................................. items.create › V1\Admin\Item\ItemsController@create
  POST            api/v1/items/delete ................................................................................................................................. V1\Admin\Item\ItemsController@delete
  GET|HEAD        api/v1/items/{item} ...................................................................................................................... items.show › V1\Admin\Item\ItemsController@show
  PUT|PATCH       api/v1/items/{item} .................................................................................................................. items.update › V1\Admin\Item\ItemsController@update
  DELETE          api/v1/items/{item} ................................................................................................................ items.destroy › V1\Admin\Item\ItemsController@destroy
  GET|HEAD        api/v1/items/{item}/edit ................................................................................................................. items.edit › V1\Admin\Item\ItemsController@edit
  GET|HEAD        api/v1/mail/config ...................................................................................................... V1\Admin\Settings\MailConfigurationController@getMailEnvironment
  POST            api/v1/mail/config ..................................................................................................... V1\Admin\Settings\MailConfigurationController@saveMailEnvironment
  GET|HEAD        api/v1/mail/drivers ......................................................................................................... V1\Admin\Settings\MailConfigurationController@getMailDrivers
  POST            api/v1/mail/test ........................................................................................................... V1\Admin\Settings\MailConfigurationController@testEmailConfig
  GET|HEAD        api/v1/me .................................................................................................................................... V1\Admin\Settings\CompanyController@getUser
  PUT             api/v1/me .............................................................................................................................. V1\Admin\Settings\CompanyController@updateProfile
  GET|HEAD        api/v1/me/settings ........................................................................................................................... V1\Admin\Settings\GetUserSettingsController
  PUT             api/v1/me/settings ........................................................................................................................ V1\Admin\Settings\UpdateUserSettingsController
  POST            api/v1/me/upload-avatar ................................................................................................................. V1\Admin\Settings\CompanyController@uploadAvatar
  GET|HEAD        api/v1/modules ........................................................................................................................................ V1\Admin\Modules\ModulesController
  GET|HEAD        api/v1/modules/check ................................................................................................................................. V1\Admin\Modules\ApiTokenController
  POST            api/v1/modules/complete ............................................................................................................ V1\Admin\Modules\CompleteModuleInstallationController
  POST            api/v1/modules/copy ................................................................................................................................ V1\Admin\Modules\CopyModuleController
  POST            api/v1/modules/download ........................................................................................................................ V1\Admin\Modules\DownloadModuleController
  POST            api/v1/modules/unzip .............................................................................................................................. V1\Admin\Modules\UnzipModuleController
  POST            api/v1/modules/upload ............................................................................................................................ V1\Admin\Modules\UploadModuleController
  GET|HEAD        api/v1/modules/{module} ................................................................................................................................ V1\Admin\Modules\ModuleController
  POST            api/v1/modules/{module}/disable ................................................................................................................. V1\Admin\Modules\DisableModuleController
  POST            api/v1/modules/{module}/enable ................................................................................................................... V1\Admin\Modules\EnableModuleController
  GET|HEAD        api/v1/next-number ................................................................................................................................. V1\Admin\General\NextNumberController
  GET|HEAD        api/v1/notes ........................................................................................................................ notes.index › V1\Admin\General\NotesController@index
  POST            api/v1/notes ........................................................................................................................ notes.store › V1\Admin\General\NotesController@store
  GET|HEAD        api/v1/notes/{note} ................................................................................................................... notes.show › V1\Admin\General\NotesController@show
  PUT|PATCH       api/v1/notes/{note} ............................................................................................................... notes.update › V1\Admin\General\NotesController@update
  DELETE          api/v1/notes/{note} ............................................................................................................. notes.destroy › V1\Admin\General\NotesController@destroy
  GET|HEAD        api/v1/number-placeholders ................................................................................................................. V1\Admin\General\NumberPlaceholdersController
  GET|HEAD        api/v1/payment-methods ........................................................................................... payment-methods.index › V1\Admin\Payment\PaymentMethodsController@index
  POST            api/v1/payment-methods ........................................................................................... payment-methods.store › V1\Admin\Payment\PaymentMethodsController@store
  GET|HEAD        api/v1/payment-methods/{payment_method} ............................................................................ payment-methods.show › V1\Admin\Payment\PaymentMethodsController@show
  PUT|PATCH       api/v1/payment-methods/{payment_method} ........................................................................ payment-methods.update › V1\Admin\Payment\PaymentMethodsController@update
  DELETE          api/v1/payment-methods/{payment_method} ...................................................................... payment-methods.destroy › V1\Admin\Payment\PaymentMethodsController@destroy
  GET|HEAD        api/v1/payments ............................................................................................................... payments.index › V1\Admin\Payment\PaymentsController@index
  POST            api/v1/payments ............................................................................................................... payments.store › V1\Admin\Payment\PaymentsController@store
  POST            api/v1/payments/delete ........................................................................................................................ V1\Admin\Payment\PaymentsController@delete
  GET|HEAD        api/v1/payments/{payment} ....................................................................................................... payments.show › V1\Admin\Payment\PaymentsController@show
  PUT|PATCH       api/v1/payments/{payment} ................................................................................................... payments.update › V1\Admin\Payment\PaymentsController@update
  DELETE          api/v1/payments/{payment} ................................................................................................. payments.destroy › V1\Admin\Payment\PaymentsController@destroy
  POST            api/v1/payments/{payment}/send .................................................................................................................... V1\Admin\Payment\SendPaymentController
  GET|HEAD        api/v1/payments/{payment}/send/preview ..................................................................................................... V1\Admin\Payment\SendPaymentPreviewController
  GET|HEAD        api/v1/recurring-invoice-frequency ......................................................................................... V1\Admin\RecurringInvoice\RecurringInvoiceFrequencyController
  GET|HEAD        api/v1/recurring-invoices .......................................................................... recurring-invoices.index › V1\Admin\RecurringInvoice\RecurringInvoiceController@index
  POST            api/v1/recurring-invoices .......................................................................... recurring-invoices.store › V1\Admin\RecurringInvoice\RecurringInvoiceController@store
  POST            api/v1/recurring-invoices/delete ............................................................................................. V1\Admin\RecurringInvoice\RecurringInvoiceController@delete
  GET|HEAD        api/v1/recurring-invoices/{recurring_invoice} ........................................................ recurring-invoices.show › V1\Admin\RecurringInvoice\RecurringInvoiceController@show
  PUT|PATCH       api/v1/recurring-invoices/{recurring_invoice} .................................................... recurring-invoices.update › V1\Admin\RecurringInvoice\RecurringInvoiceController@update
  DELETE          api/v1/recurring-invoices/{recurring_invoice} .................................................. recurring-invoices.destroy › V1\Admin\RecurringInvoice\RecurringInvoiceController@destroy
  GET|HEAD        api/v1/roles ........................................................................................................................... roles.index › V1\Admin\Role\RolesController@index
  POST            api/v1/roles ........................................................................................................................... roles.store › V1\Admin\Role\RolesController@store
  GET|HEAD        api/v1/roles/{role} ...................................................................................................................... roles.show › V1\Admin\Role\RolesController@show
  PUT|PATCH       api/v1/roles/{role} .................................................................................................................. roles.update › V1\Admin\Role\RolesController@update
  DELETE          api/v1/roles/{role} ................................................................................................................ roles.destroy › V1\Admin\Role\RolesController@destroy
  GET|HEAD        api/v1/search .......................................................................................................................................... V1\Admin\General\SearchController
  GET|HEAD        api/v1/search/user ................................................................................................................................ V1\Admin\General\SearchUsersController
  GET|HEAD        api/v1/settings .................................................................................................................................. V1\Admin\Settings\GetSettingsController
  POST            api/v1/settings ............................................................................................................................... V1\Admin\Settings\UpdateSettingsController
  GET|HEAD        api/v1/supported-currencies ....................................................................................................... V1\Admin\ExchangeRate\GetSupportedCurrenciesController
  GET|HEAD        api/v1/tax-types ............................................................................................................ tax-types.index › V1\Admin\Settings\TaxTypesController@index
  POST            api/v1/tax-types ............................................................................................................ tax-types.store › V1\Admin\Settings\TaxTypesController@store
  GET|HEAD        api/v1/tax-types/{tax_type} ................................................................................................... tax-types.show › V1\Admin\Settings\TaxTypesController@show
  PUT|PATCH       api/v1/tax-types/{tax_type} ............................................................................................... tax-types.update › V1\Admin\Settings\TaxTypesController@update
  DELETE          api/v1/tax-types/{tax_type} ............................................................................................. tax-types.destroy › V1\Admin\Settings\TaxTypesController@destroy
  GET|HEAD        api/v1/timezones .................................................................................................................................... V1\Admin\General\TimezonesController
  POST            api/v1/transfer/ownership/{user} .................................................................................................. V1\Admin\Company\CompaniesController@transferOwnership
  GET|HEAD        api/v1/units ........................................................................................................................... units.index › V1\Admin\Item\UnitsController@index
  POST            api/v1/units ........................................................................................................................... units.store › V1\Admin\Item\UnitsController@store
  GET|HEAD        api/v1/units/create .................................................................................................................. units.create › V1\Admin\Item\UnitsController@create
  GET|HEAD        api/v1/units/{unit} ...................................................................................................................... units.show › V1\Admin\Item\UnitsController@show
  PUT|PATCH       api/v1/units/{unit} .................................................................................................................. units.update › V1\Admin\Item\UnitsController@update
  DELETE          api/v1/units/{unit} ................................................................................................................ units.destroy › V1\Admin\Item\UnitsController@destroy
  GET|HEAD        api/v1/units/{unit}/edit ................................................................................................................. units.edit › V1\Admin\Item\UnitsController@edit
  POST            api/v1/update/copy ................................................................................................................................... V1\Admin\Update\CopyFilesController
  POST            api/v1/update/delete ............................................................................................................................... V1\Admin\Update\DeleteFilesController
  POST            api/v1/update/download .......................................................................................................................... V1\Admin\Update\DownloadUpdateController
  POST            api/v1/update/finish .............................................................................................................................. V1\Admin\Update\FinishUpdateController
  POST            api/v1/update/migrate ............................................................................................................................ V1\Admin\Update\MigrateUpdateController
  POST            api/v1/update/unzip ................................................................................................................................ V1\Admin\Update\UnzipUpdateController
  GET|HEAD        api/v1/used-currencies ................................................................................................................. V1\Admin\ExchangeRate\GetUsedCurrenciesController
  GET|HEAD        api/v1/users .......................................................................................................................... users.index › V1\Admin\Users\UsersController@index
  POST            api/v1/users .......................................................................................................................... users.store › V1\Admin\Users\UsersController@store
  POST            api/v1/users/delete ................................................................................................................................ V1\Admin\Users\UsersController@delete
  GET|HEAD        api/v1/users/{user} ..................................................................................................................... users.show › V1\Admin\Users\UsersController@show
  PUT|PATCH       api/v1/users/{user} ................................................................................................................. users.update › V1\Admin\Users\UsersController@update
  DELETE          api/v1/users/{user} ............................................................................................................... users.destroy › V1\Admin\Users\UsersController@destroy
  POST            api/v1/{company}/customer/auth/password/email ............................................................................... V1\Customer\Auth\ForgotPasswordController@sendResetLinkEmail
  POST            api/v1/{company}/customer/auth/reset/password ................................................................... customer.password.reset › V1\Customer\Auth\ResetPasswordController@reset
  GET|HEAD        api/v1/{company}/customer/bootstrap .............................................................................................................. V1\Customer\General\BootstrapController
  GET|HEAD        api/v1/{company}/customer/countries ................................................................................................................. V1\Admin\General\CountriesController
  GET|HEAD        api/v1/{company}/customer/dashboard .............................................................................................................. V1\Customer\General\DashboardController
  POST            api/v1/{company}/customer/estimate/{estimate}/status ....................................................................................... V1\Customer\Estimate\AcceptEstimateController
  GET|HEAD        api/v1/{company}/customer/estimates ....................................................................................................... V1\Customer\Estimate\EstimatesController@index
  GET|HEAD        api/v1/{company}/customer/estimates/{id} ................................................................................................... V1\Customer\Estimate\EstimatesController@show
  GET|HEAD        api/v1/{company}/customer/expenses .......................................................................................................... V1\Customer\Expense\ExpensesController@index
  GET|HEAD        api/v1/{company}/customer/expenses/{id} ...................................................................................................... V1\Customer\Expense\ExpensesController@show
  GET|HEAD        api/v1/{company}/customer/invoices .......................................................................................................... V1\Customer\Invoice\InvoicesController@index
  GET|HEAD        api/v1/{company}/customer/invoices/{id} ...................................................................................................... V1\Customer\Invoice\InvoicesController@show
  GET|HEAD        api/v1/{company}/customer/me ............................................................................................................... V1\Customer\General\ProfileController@getUser
  GET|HEAD        api/v1/{company}/customer/payment-method ..................................................................................................... V1\Customer\Payment\PaymentMethodController
  GET|HEAD        api/v1/{company}/customer/payments .......................................................................................................... V1\Customer\Payment\PaymentsController@index
  GET|HEAD        api/v1/{company}/customer/payments/{id} ...................................................................................................... V1\Customer\Payment\PaymentsController@show
  POST            api/v1/{company}/customer/profile .................................................................................................... V1\Customer\General\ProfileController@updateProfile
  POST            auth/logout .............................................................................................................................................................................. 
  GET|POST|HEAD   broadcasting/auth ............................................................................................................. Illuminate\Broadcasting › BroadcastController@authenticate
  GET|HEAD        customer/estimates/view/{email_log} .................................................................................................. estimate › V1\Customer\EstimatePdfController@getPdf
  GET|HEAD        customer/estimates/{email_log} ............................................................................................................. V1\Customer\EstimatePdfController@getEstimate
  GET|HEAD        customer/invoices/view/{email_log} ..................................................................................................... invoice › V1\Customer\InvoicePdfController@getPdf
  GET|HEAD        customer/invoices/{email_log} ................................................................................................................ V1\Customer\InvoicePdfController@getInvoice
  GET|HEAD        customer/payments/view/{email_log} ..................................................................................................... payment › V1\Customer\PaymentPdfController@getPdf
  GET|HEAD        customer/payments/{email_log} ................................................................................................................ V1\Customer\PaymentPdfController@getPayment
  GET|HEAD        estimates/pdf/{estimate} .................................................................................................................................... V1\PDF\EstimatePdfController
  GET|HEAD        forgot-password .......................................................................................................................................................... forgot-password
  GET|HEAD        installation ..................................................................................................................................................................... install
  GET|HEAD        invoices/pdf/{invoice} ....................................................................................................................................... V1\PDF\InvoicePdfController
  POST            login ................................................................................................................................................ V1\Admin\Auth\LoginController@login
  GET|HEAD        login .............................................................................................................................................................................. login
  GET|HEAD        modules/scripts/{script} ..................................................................................................................................... V1\Modules\ScriptController
  GET|HEAD        modules/styles/{style} ........................................................................................................................................ V1\Modules\StyleController
  GET|HEAD        payments/pdf/{payment} ....................................................................................................................................... V1\PDF\PaymentPdfController
  GET|HEAD        reports/expenses/{expense}/download-receipt ............................................................................................................. V1\PDF\DownloadReceiptController
  GET|HEAD        reports/expenses/{expense}/receipt ................................................................................................................ V1\Admin\Expense\ShowReceiptController
  GET|HEAD        reports/expenses/{hash} ......................................................................................................................... V1\Admin\Report\ExpensesReportController
  GET|HEAD        reports/profit-loss/{hash} .................................................................................................................... V1\Admin\Report\ProfitLossReportController
  GET|HEAD        reports/sales/customers/{hash} ............................................................................................................. V1\Admin\Report\CustomerSalesReportController
  GET|HEAD        reports/sales/items/{hash} ..................................................................................................................... V1\Admin\Report\ItemSalesReportController
  GET|HEAD        reports/tax-summary/{hash} .................................................................................................................... V1\Admin\Report\TaxSummaryReportController
  GET|HEAD        reset-password/{token} .................................................................................................................................................... reset-password
  GET|HEAD        sanctum/csrf-cookie .................................................................................................... sanctum.csrf-cookie › Laravel\Sanctum › CsrfCookieController@show
  POST            {company}/customer/login ................................................................................................................................ V1\Customer\Auth\LoginController
  POST            {company}/customer/logout ................................................................................................................................................................ 
  GET|HEAD        {company}/customer/{vue?} ............................................................................................................................................. customer.dashboard`

I'm using selfhost without any docker.

1. Nginx with PHP 8.3 FPM
2. It was working with an old crater installation. Has anything changed in the new version? Is it possible to provide nginx config files?

**Comment by mchev** [comment]
I'm not sure the current version works with PHP8.3. The v2 will (on branch develop)

**Comment by gdarko** [comment]
Hey @razarahil ,

Here is a sample nginx config for the app:

```
server {
    listen 80;
    listen [::]:80;
    server_name example.com;
    root /srv/example.com/public;
 
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
 
    index index.php;
 
    charset utf-8;
 
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
 
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
 
    error_page 404 /index.php;
 
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
 
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```

Taken from https://laravel.com/docs/10.x/deployment#nginx

Make sure you set the fastcgi_pass to the exact php-fpm.sock file. I'd suggest installing PHP-FPM 8.1 and 8.2 and try with it.

Best Regards,
Darko
