### ISSUE TITLE
Bug: The report tab downloads a pdf as soon as opening it

### ISSUE THREAD

**Issue by RappyTV** [InvoiceShelf/InvoiceShelf#122]
**Describe the bug**
When trying to open the `/admin/reports` route (and any of the subsections) a pdf will be downloaded instantly without clicking on "Download PDF"

**Expected behavior**
The pdf not being downloaded until the "Download PDF" button is clicked

**Screenshots**

https://github.com/user-attachments/assets/bf6aef43-63d6-4682-8774-7383e9772600

**Please complete the following information:**
- InvoiceShelf version: idk i'm using the docker compose file with the nightly build. the version is not being logged anywhere
- PHP version: ??
- Database type and version: postgres:15

**Optional info**
- Server: Debian
- OS: Windows
- Browser: Firefox

**Comment by rihards-simanovics** [comment]
looks like a Firefox issue where instead of embedding it downloads the embedded PDF. can you try opening inside incognito and ensure no other plugins are enabled.

**Comment by RappyTV** [comment]
I don't have any instances running anymore unfortunately.

**Comment by rihards-simanovics** [comment]
Closing as user nor me can replicate the issue.
