### ISSUE TITLE
Download button not working on github page

### ISSUE THREAD

**Issue by EnesA20** [InvoiceShelf/InvoiceShelf#129]
https://invoiceshelf.com/downloads not working on github page

**Comment by gdarko** [comment]
Hey @EnesA20 

You can download the software directly on invoiceshelf.com  homepage (not /downloads)

![image](https://github.com/user-attachments/assets/71e3005c-3ed6-4ee9-a95b-12caf764df0a)

Best Regards,
Darko

**Comment by EnesA20** [comment]
I know but the link does not work on the github page: https://github.com/InvoiceShelf/InvoiceShelf?tab=readme-ov-file#download

**Comment by nedlane** [comment]
I just added a PR (#130) to fix it so it should just easy for the maintainers to just approve and merge the one line change

**Comment by mchev** [comment]
Fixed by https://github.com/InvoiceShelf/InvoiceShelf/commit/0c0de64549191dd730832bda1357be80657ddb76
