### ISSUE TITLE
Include a Tax ID field in both customer creation and invoices

### ISSUE THREAD

**Issue by alfonsolr09** [InvoiceShelf/InvoiceShelf#133]
**Describe the bug**
IN SPAIN WHEN GENERATING AN INVOICE IT IS MANDATORY TO ADD THE COMPANY CIF OR TAX ID, I DO NOT SEE THE OPTION OF BEING ABLE TO ADD IT IN THE CUSTOMER CREATION FORM

**Expected behavior**
ADD THE FIELD TO ADD THE TAX ID

**Comment by alfonsolr09** [comment]
https://github.com/crater-invoice/crater/issues/746

**Comment by alfonsolr09** [comment]
https://github.com/crater-invoice/crater/issues/856

**Comment by alfonsolr09** [comment]
same problems a few years before

**Comment by mchev** [comment]
I think it is mandatory to display the company Tax ID, not the customer one. This is already posssible in the company settings.

![Capture d’écran 2024-08-01 à 07 24 28](https://github.com/user-attachments/assets/bb6892dc-fb5c-4f2d-a9b4-5da4184f0109)

And you can display it in every invoice in the Invoice Customization Settings 👍 
![Capture d’écran 2024-08-01 à 07 27 26](https://github.com/user-attachments/assets/f986bff9-d71f-4998-a9d5-2e653cdcf714)

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
