### ISSUE TITLE
Editing the price in an invoice draft changes the payment status of the invoice

### ISSUE THREAD

**Issue by ttytm** [InvoiceShelf/InvoiceShelf#134]
**Bug description**
Editing the price in an invoice draft marks it as partially paid.

**Expected behavior**
Payment status remains unchanged.

**Repro**
- Clone an invoice (verify it's status is unpaid). 
- Edit the price of the item in the invoice.

```
InvoiceShelf version: 1.3.0
Database type and version: PG
OS: Linux 6.6.42-1-lts x86_64 GNU/Linux
Browser: Chromium-based
```

**Comment by gdarko** [comment]
Thanks for reporting the issue @ttytm  

This is fixed in the incoming 2.0.0 version (468aec6bc1edcdb0d9dd944c8a88e6c0402d2d11)
