### ISSUE TITLE
Artisan::call('migrate --seed --force'); is not executing fully

### ISSUE THREAD

**Issue by RasniNathees** [InvoiceShelf/InvoiceShelf#135]
**Describe the bug**
When installing the application the Artisan::call('migrate --seed --force'); command is not executing fully when called within a Laravel controller. This causes the script to hang and prevents further execution. Other Artisan commands before this work as expected.

**Expected behavior**
The Artisan::call('migrate --seed --force'); command should execute fully, running all migrations and seeding the database without causing the script to hang.

**Screenshots**

**Please complete the following information:**
- InvoiceShelf version: current version
- PHP version: 8.3
- Database type and version: mysql 8+ 

**Optional info**
- OS:  ubuntu 22.04
- Browser: chrome, safari

**Comment by gdarko** [comment]
Hey,

What do you see in your `laravel.log` file? The file can be found in `storage/logs`.

Best Regards,
Darko

**Comment by RasniNathees** [comment]
Hey Darko,

Thank you for your response.

I checked the laravel.log file located in storage/logs, but it didn't provide any error logs related to this issue.

Additionally, I added logs before and after each line of the controller method. The logs show that the script stops executing when it hits the Artisan::call('migrate --seed --force'); command. The process hangs, and only 2-3 tables are created in the database before it stops.

**Comment by onensensy** [comment]
There is a 504(timeout) on the browser console

**Comment by gdarko** [comment]
I can't reproduce the issue so far. Which database exactly you are using. MySQL or MariaDB?

**Comment by carlosrl19** [comment]
I have the same problem, Artisan::call('migrate --seed --force'); does not run completely, sometimes it creates 5, 6, 8, 10, 10, 10, 20, 28 tables, but never completely, any solution? This happens (clearly) when I am in the installer, right at the database configuration step.

What did I do?
1. Download InvoiceShelf from git clone https://github.com/InvoiceShelf/InvoiceShelf.git
2. Give permissions 775 to the storage/framework storage/logs bootstrap/cache folders.
3. Copy the .env.example file to .env and set up the database.
4. Execute:
composer install
npm install
npm build (even if you run npm run dev, it generates the same error)
php artisan key:generate

5. Here something curious happens, if I run php artisan migrate, at the time of being in the installer tells me that the database must be empty, so I must always be in a loop of creating and deleting the database that I want to use.

Info:
InvoiceShelf Version: 2.0.0-RC1
PHP version: PHP 8.2.20
Database: mariadb Ver 15.1 Distrib 10.11.6-MariaDB, for debian-linux-gnu (x86_64) using EditLine wrapper

OS: Debian GNU/Linux 12 (bookworm) x86_64 
Browser: Brave Browser 127.1.68.141 


Translated with DeepL.com (free version)

**Comment by mchev** [comment]
Is this issue still present in version 2?

**Comment by rihards-simanovics** [comment]
Closing as stale, @RasniNathees if issue persists, please re-open.

**Comment by seeni-dev** [comment]
This issue happened again for me today with sqlite. So, doing the migrations myself via `php artisan migrate --seed --force`. (Same as what the code does).
It took `3m37.841s` in my system. So, understandable that request was timed out.
Maybe we should make db setup via async&poll or load via a schema file?
