### ISSUE TITLE
Failed to create new template

### ISSUE THREAD

**Issue by Lulu300** [InvoiceShelf/InvoiceShelf#139]
**Describe the bug**
When I try to create a new template with the command (from the doc) `docker-compose exec invoice php artisan make:template invoice2-fr` it return an error message. Then, if i try to edit an invoice I've got an error and I can't do anything on the web page.

**Expected behavior**
Template must be successfully created.

**Screenshots**
![Screenshot 2024-08-11 164340](https://github.com/user-attachments/assets/c494f862-67a6-42e9-8387-9451bf7098ce)
![Screenshot 2024-08-11 164328](https://github.com/user-attachments/assets/894af00f-0caa-4762-b19a-5262b454af78)

**Please complete the following information:**
- InvoiceShelf version: 2.0.0 alpha (Docker container alpha tag) and 1.3.0 (Docker container nigthly tag)
- PHP version: 8.2.20
- Database type and version: PGSQL v16

**Optional info**
- OS:  Debian 12
- Browser: Firefox

**Comment by PontusTideman** [comment]
@Lulu300 I've found the issue, but don't have the time right now tonight to fix it. Going to test it tomorrow, and if my fix is working then I'm going to push the fix upstream.

**Comment by LU-386** [comment]
@PontusTideman hey, did you fix this already? I just ran into the problem too

**Comment by PontusTideman** [comment]
> @PontusTideman hey, did you fix this already? I just ran into the problem too 

@LU-386 Yes, kind off. It's manual work to get it to work. And we decided to not push the "fix" upstream because we don't know if we are going to get any new bugs. 🫣🤪

I will post the fix soon.

**Comment by rihards-simanovics** [comment]
linked to #252
