### ISSUE TITLE
Payment QR code on invoices

### ISSUE THREAD

**Issue by csoscd** [InvoiceShelf/InvoiceShelf#140]
It would be great if a payment QR code could be printed on each invoice. It needs individuelly be generated because it does not only need to contain the bank account infortmation of the receiptient but also the invoice number as purpose for the transaction. Ideally, it would be configurable which information would be part of the purpose of the tranbsaction.

**Comment by JeroenSteen** [comment]
I suggested SEPA QR, like in this library: https://github.com/smhg/sepa-qr-data-php

**Comment by PontusTideman** [comment]
Or the best way is the ability to just add a static QR code from a PNG/SVG file.
That way it supports more payment options.

**Comment by csoscd** [comment]
In my opinion, a generic version would not be satisfactory. I would like to give thwe customer the easiest option to pay. It would be best if the customer could scan a QR code with the banking app and initiate the payment without having to enter any data. Having a generic one would at least require to enter the amount to pay and the invoice number (or whatever is identifying).

**Comment by csoscd** [comment]
But isn't a static one already now possible by adjusting the template for PDF?

**Comment by JeroenSteen** [comment]
The most convenient way would be a dynamicly generated QR-code (SEPA), maybe based on this data:

- Name of the Beneficiary
- Account number of the Beneficiary
- Amount of the Credit Transfer (EUR)
- Information (Invoice number)
- BIC of the Beneficiary Bank
- Party number
- BIC of the Beneficiary Bank
- Purpose of the Credit Transfer
- Beneficiary to originator information

See also: https://epc-qr.eu/?form

Staticly created is maybe great for the same Amount, but then you don't have unique Invoice numer in the data.

**Comment by rihards-simanovics** [comment]
linked to #252
