### ISSUE TITLE
CSRF Token Mismatch and Domain Verification Failure in InvoiceShelf Setup on Shared Hosting

### ISSUE THREAD

**Issue by Anonymo** [InvoiceShelf/InvoiceShelf#148]
### **Describe the bug**
During the setup of InvoiceShelf on shared hosting, I encountered a persistent **CSRF Token Mismatch** and **Domain Verification Failure** when attempting to complete the domain verification process. Despite following troubleshooting steps such as clearing caches, adjusting session configurations, and excluding the route from CSRF protection, the issue persists.

### **Expected behavior**
The domain verification should complete successfully, and the application should proceed without throwing a CSRF token mismatch error.

### **Steps to reproduce the issue**
1. Set up InvoiceShelf on A2 shared hosting.
2. Configure the `.env` file as described in the documentation.
3. Attempt to run domain verification.
4. Receive a **CSRF Token Mismatch** and **Domain Verification Failure**.

### **Screenshots**
Include any screenshots of the error page.

### **Please complete the following information:**
- **InvoiceShelf version:** [Please specify the version you're using]
- **PHP version:** 8.2
- **Database type and version:**
### **Optional info**
- **OS:** [e.g., Shared hosting on Linux (A2 Hosting)]
- **Browser:** [Chrome]
![invoiceshelferror](https://github.com/user-attachments/assets/373465b9-0f00-4982-8e63-3b6e883ff94f)

**Steps I’ve Tried:**

1. **Configured the `.env` File**:
   - I ensured the `APP_URL` and `SESSION_DOMAIN` were set correctly and generated a new application key using `php artisan key:generate`. I confirmed that the `.env` file was updated with the new key.

2. **Checked the Session Configuration**:
   - Since the `config/session.php` file was missing from the project, I copied it from `vendor/laravel/framework/config/` into the `config/` directory. I updated it to enable secure cookies by setting `'secure' => env('SESSION_SECURE_COOKIE', true)`.

3. **Disabled CSRF Protection Temporarily**:
   - I added the domain verification URL to the `$except` array in `app/Http/Middleware/VerifyCsrfToken.php` to exclude it from CSRF protection temporarily, just to check if that was causing the CSRF token mismatch error.

4. **Cleared Cache**:
   - After each change, I ran the following commands to clear any cached configurations:
     ```bash
     php artisan config:clear
     php artisan cache:clear
     php artisan view:clear
     ```

**Comment by Anonymo** [comment]
After trying several approaches, I finally cleared the cookies, and that resolved the issue and allowed me to move forward.

**Comment by AliMughal169** [comment]
i opened invoiceshelf.test on seperate Brave browser and it worked for me
