### ISSUE TITLE
Cannot connect to RDS MySQL instance

### ISSUE THREAD

**Issue by amanattrish** [InvoiceShelf/InvoiceShelf#152]
**Describe the bug**
I followed the docker installation documentation here - https://docs.invoiceshelf.com/install/docker.html
It is spinning up a db and invoiceShelf code in two separate containers.
Rather I wanted to use my existsing DB instance in AWS RDS (MySQL DB), so I removed **invoiceshelf_db** service and changed the DB credentials in ENV of **invoiceshelf** service in docker compose file. Finally I also removed "depends_on:" from **invoiceshelf**.

When I'm running 'docker compose up -d" it gives me error on localhost:90
Seems like I need to run Db migrations to populate Db in AWS RDS instance. 

**Expected behavior**
There should be a documentation about how to connect with DB in AWS RDS instance.

**Screenshots**
![1 (1)](https://github.com/user-attachments/assets/6edb2758-43ac-4ccc-a2ac-b9142a70c519)

**Please complete the following information:**
- InvoiceShelf version: Latest
- PHP version: Latest
- Database type and version: MySQL

**Optional info**
- OS:  MacOS
- Browser: Brave

**Comment by amanattrish** [comment]
Is anybody following issues in this repository?

**Comment by mchev** [comment]
I'm not entirely sure about your configuration, but if the system is correctly connected to your RDS database, you may just need to run the migration once with `php artisan migrate --seed`

**Comment by amanattrish** [comment]
Where to run this command once docker container runs correctly?

**Comment by mchev** [comment]
I'm not a docker user but i think with docker compose it's something like `docker-compose exec invoiceshelf php artisan migrate`. Where invoiceshelf is the service name

**Comment by amanattrish** [comment]
Okay it worked. I got the connection as well.

During the installation process at the route `/installation`, when I put DB details, it give `Database should be empty` error. I checked, all my tables are empty. Any idea what's happening?

**Comment by amanattrish** [comment]
seems like it is coming from `/app/Space/EnvironmentManage.php`, line 129.

I'm confused here, the migartions created the users table, but the code doesn't want it. Am I missing something here?
<img width="666" alt="image" src="https://github.com/user-attachments/assets/a5e01efa-6055-4b24-adb3-3fd0c2e7bc9b">

**Comment by mchev** [comment]
During the installation process, when you set your database credentials, there is a checkbox at the bottom to empty the db. This should work.

**Comment by amanattrish** [comment]
Thanks for reply @mchev 

I don't see any checkbox, see screenshot
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/39c530b3-b9b8-4d21-bbaf-924e5ef6f3c6">

**Comment by mchev** [comment]
> Okay it worked. I got the connection as well.
> 
> During the installation process at the route `/installation`, when I put DB details, it give `Database should be empty` error. I checked, all my tables are empty. Any idea what's happening?
> 
> I first run migrations, it didn't work. I then run the seed, it didn't work out either.

The db should not have any table before the installation process. Juste create the database with nothing in it. The go to the installation page.

**Comment by amanattrish** [comment]
Thanks, it worked out.
