### ISSUE TITLE
Milestone and per hour based item pricing

### ISSUE THREAD

**Issue by amanattrish** [InvoiceShelf/InvoiceShelf#155]
**Is your feature request related to a problem? Please describe.**
Right now it seems like invoiceshelf only supports fixed price based item. There are some items like - renting a car, giving professional service which needs per hour based item pricing. Similarly, there could be projects for customers which involves milestone based pricing.

**Describe the solution you'd like**
Provide options for item pricing based on milestone and per hour basis as well

**Describe alternatives you've considered**
Odoo sales

**Comment by gdarko** [comment]
Hey @amanattrish , 

It is possible to add "hour" as unit, that should solve the issue, i believe. I am doing this for my own invoicing currently.

Best,
DG

**Comment by mchev** [comment]
Hi @amanattrish! Like @gdarko mentioned, you can always set custom units for your items. That said, pricing based on milestones isn’t something most individuals or small businesses need to deal with frequently, in my experience. (Correct me if the milestone use case is particularly useful in some cases!)

Invoiceshelf is designed to keep invoicing simple and accessible for small businesses. The idea isn’t to build a large, feature-heavy CRM like Odoo, but rather to offer an invoicing tool that’s easy to use and does its job really well.

Hope that helps! :)
