### ISSUE TITLE
Unable to complete installation

### ISSUE THREAD

**Issue by Rishan99** [InvoiceShelf/InvoiceShelf#158]
**Describe the bug**
3rd step of installation widget, i have added dataabase username, database name, pw 
SQLSTATE[28000] [1045] Access denied for user 'xxxx'@'localhost' (using password: YES)
select * from `settings` where `option` = profile_complete limit 1

I checked the database manually and other tables were created and setting table has a row with option ''profile_complete"
Therefore it cannot be access related since, other tables were created, The user has full access to the database

**Please complete the following information:**
- InvoiceShelf version: Version 2.0.0
- PHP version: 8.2
- Database type and version:  mysql  Ver 15.1 Distrib 10.6.19-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by mchev** [comment]
Have you tried `127.0.0.1` instead of `localhost` ? Is the port ok too ?
It is a new installation or an upgrade ? If it's a new installation, the database should be empty.
Docker or manual installation ?

**Comment by Rishan99** [comment]
yes i have tried both 127.0.0.1 and localhost, yes port is ok too
Manual Installation, and it is a fresh installation from creating new database 
Initially schema is empty, after running third step of installation
SQLSTATE[28000] [1045] Access denied for user 'xxxx'@'localhost' (using password: YES)
select * from settings where option = profile_complete limit 1
This error comes up and when i look at the database, multiple tables are created

**Comment by Rishan99** [comment]
@mchev  Tried it
and verified the password with double quote and without [ initially it was saved without quote]
and result is same, when i redo fresh installation with new database, it is same, migration is happening i.e all the required tables are created but 
SQLSTATE[28000] [1045] Access denied for user 'xxxx'@'localhost' (using password: YES)
select * from settings where option = profile_complete limit 1 
this occurs still

**Comment by mchev** [comment]
> I changed the location of database to diff remote server and tried connecting it, same error persist regardless

Ok that strange. I guess you could try with SQLite to see if the problem persist.

**Comment by Rishan99** [comment]
Seems to be related to the hosting i have tested with
working without issue locally
Weird thing is migration is done without any access issue, but only throws when trying to check the option value from settings table

**Comment by mchev** [comment]
@Rishan99 Did you manage to get it working on another host? Was it an issue with the Nginx or database configuration?

If you've found a solution to your specific problem, it would be helpful to share it. We could consider adding this use case to the documentation for others.

**Comment by rihards-simanovics** [comment]
@Rishan99 I'm not a bot, but just want to let you if the issue is resolved or you need further assistance, please let us know. Otherwise the issue will be made stale in around 34 hours and then closed.

**Comment by Rishan99** [comment]
@mchev @rihards-simanovics  Sorry been busy past few days
 Yes i managed to get it working,
 I wrapped password in double quotes
 DB_PASSWORD="MyPw"
 And restarted by website
 I tried this method before but doesn't seem to work before, but now its working perfectly fine
 
 Thanks @mchev  for help

**Comment by rihards-simanovics** [comment]
> Hi, i'm facing the exact same issue. I've tried local hosting and online.. same issue

hey @GroupeLudix, this doesn't seem like a bug, but perhaps a misconfiguration. I advice that you join our discord server for support, you can find the link to discord by clicking on [Question & Discussion](https://github.com/InvoiceShelf/InvoiceShelf/issues/new/choose)

**Comment by nmincone** [comment]
I stumbled on this post and decided to give this a try tonight. Ran into the same error, only diff is that the Database Host should be 'invoiceshelf_db', now the error I get is 'SQLSTATE[HY000] [1045] Access denied for user 'invoiceshelf' @'172.20.0.3' (using password: YES)'

**Comment by jleroy** [comment]
I ran into the same issue. 

My password contains a hash symbol (`#`). I’ve double-quoted it in the `.env` file, but the installation wizard always remove them.
I’ve updated my password to replace the hash with another character, updated the `.env`file, ran `php artisan optimize:clear` and then restarted the install wizard and everything worked fine.
