### ISSUE TITLE
Recurring Invoice Subject not translated 

### ISSUE THREAD

**Issue by Honigbrot** [InvoiceShelf/InvoiceShelf#164]
Updated to 2.0.
When I send a recurring invoice manually it shows the newly translated string (in my case de: "Neue Rechnung"). However when I automatically send an invoice it stills defaults to "New Invoice".

I had a look at RecurringInvoice.php but cant find the reason why this shouldn't send the translated string

```
 //send automatically
        if ($this->send_automatically == true) {
            $data = [
                'body' => CompanySetting::getSetting('invoice_mail_body', $this->company_id),
                'from' => config('mail.from.address'),
                'to' => $this->customer->email,
                'subject' => trans('invoices')['new_invoice'],
                'invoice' => $invoice->toArray(),
                'customer' => $invoice->customer->toArray(),
                'company' => Company::find($invoice->company_id),
            ];

            $invoice->send($data);
        }
```

**Comment by Honigbrot** [comment]
I think I found the culprit.
I had to add APP_LOCALE=de manually to my .env. Somehow this was not set automatically.

**Comment by rihards-simanovics** [comment]
@Honigbrot did this solve the issue?

@mchev maybe we should keep this one open as it seems like a genuine bug if it didn't change the locale automatically.

**Comment by Honigbrot** [comment]
Yeah this actually fixed it for me. Keep in mind that I have been using the same .env file since Crater. I realised I was missing APP_LOCALE entirely (it is present in the .env.example!), so maybe this has been a bug with crater that just now came into effect!

**Comment by rihards-simanovics** [comment]
I will close as complete for now but if anyone has a similar issue, we can re-open and investigate further.
