### ISSUE TITLE
Amharic Locale Support

### ISSUE THREAD

**Issue by adnan4k** [InvoiceShelf/InvoiceShelf#168]
** I hope this message finds you well. I would like to formally request the addition of an Amharic locale to InvoiceShelf.

**Amharic is the official language of Ethiopia and is spoken by millions of people. Adding support for this locale would enhance accessibility and user experience for Amharic speakers.

**Comment by rihards-simanovics** [comment]
> ** I hope this message finds you well. I would like to formally request the addition of an Amharic locale to InvoiceShelf.
> 
> **Amharic is the official language of Ethiopia and is spoken by millions of people. Adding support for this locale would enhance accessibility and user experience for Amharic speakers.

Hey @adnan4k, Thanks for Suggestion. If you speak it, you could help out? We can't translate languages which we don't speak, and sometimes even AI machine translation isn't perfect, but if you are proficient in both English and Amharic feel free to download the https://github.com/InvoiceShelf/InvoiceShelf/blob/master/lang/en.json file and use it as a template, once you translate all the entries, we can help you make a formal PR.

**Comment by mchev** [comment]
Help us translate on :
https://crowdin.com/project/invoiceshelf

You can `Request New Language` on it.

**Comment by rihards-simanovics** [comment]
Closing for now as the initial question has been answered, can be reopened once the crowding work begins.
