### ISSUE TITLE
Laravel Modules

### ISSUE THREAD

**Issue by karneaud** [InvoiceShelf/InvoiceShelf#170]
Hey guys, 

I'm new to "Crater/ Invoice Shelf" but not new to Laravel/ VueJS. I'm currently using InvoiceNinja along with a couple of clients of mines but i'm looking to switch. I knew of crater from before but now see this. I'm particularly interested in migrating from IN to IS and adding custom payment methods by way of Modules as I have a couple of custom laravel modules to port over.

Can you tell me what the ecosystem is like for development and whether this is production ready? I do have a couple clients that would be interested in migrating if it can be done without data loss.

Also if there is need for help let me know. I might be able to assist.

**Comment by rihards-simanovics** [comment]
@karneaud are you the `@kendall` on discord? if so, we may continue the conversation there as this seems more like a question/discussion.

**Comment by rihards-simanovics** [comment]
closing as stale.
