### ISSUE TITLE
Implementation of ZUGFeRD standard for electronic invoicing in Germany

### ISSUE THREAD

**Issue by Brovning** [InvoiceShelf/InvoiceShelf#175]
Is it planned to implement the ZUGFeRD standard for electronic invoicing in Germany?

What is ZUGFeRD?
ZUGFeRD is a cross-industry data format for electronic invoice data exchange that was developed by the Forum for Electronic Invoicing Germany (FeRD) - with support from the Federal Ministry of Economics and Energy. The ZUGFeRD data format is based on the Directive 2014/55/EU of 16 April 2014 on electronic invoicing for public contracts and on the EN16931 standard published on 28 June 2017. Also, the Cross-Industry Invoice (CII) of UN/CEFACT and the ISO standard 19005-3:2012 (PDF/A-3) are also taken into account as of ZUGFeRD 2.0.

The areas of application for this hybrid invoice format are diverse. ZUGFeRD can be used in B2B, B2G, and B2C business transactions.

Description of the Standard:
https://www.ferd-net.de/standards/zugferd-2.3/zugferd-2.3.html

**Comment by krombel** [comment]
goes in the same direction as https://github.com/InvoiceShelf/InvoiceShelf/issues/163

**Comment by rihards-simanovics** [comment]
duplicate https://github.com/InvoiceShelf/InvoiceShelf/issues/163

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
