### ISSUE TITLE
Sale tax percent limit

### ISSUE THREAD

**Issue by EricPoonXYZ** [InvoiceShelf/InvoiceShelf#176]
Hi, 

I have problem to set the tax and our sale tax is 8.875%. please help.

**Comment by mchev** [comment]
Hi @EricPoonXYZ, for reporting bugs and feature requests, please use the GitHub issues.
For support, feel free to ask here: https://discord.gg/BDue7TXQ.

**Comment by rihards-simanovics** [comment]
Hey @EpicPoonXYZ, as @mchev mentioned GitHub issues are for issues, bug reports and feature requests.

If you have a question regarding the use of the app or require support, please join out Discord server.

Link above will expire at some point, and I unfortunately can't renew it but here is another link that never expires: https://discord.gg/hwg2FtwWHW or simply use one mentioned in README.md in the root of the project.

Closing as invalid.
