### ISSUE TITLE
Negative Taxes (Spain IRPF)

### ISSUE THREAD

**Issue by acobrerosf** [InvoiceShelf/InvoiceShelf#18]
Hi all,

I am a happy Crater user and just discovered this fork right now. Really excited to see the project won't just die.

I just want to point out something we already discussed in the Crater repo here: https://github.com/crater-invoice/crater/issues/1023

In some countries we have negative taxes and in my last comment I explain how you can manually sort it out. There seems to be a commit from last week from someone applying the fix to Crater itself so probably you guys could just get the code from there?

If there is anything else I can help you with let me know.

**Comment by gdarko** [comment]
Hey @acobrerosf 

This will be implemented in the coming version.

Thanks for the suggestions.

Best Regards,
Darko

**Comment by gdarko** [comment]
Merged #25 - Can be closed.
