### ISSUE TITLE
PDF is generated and error occurs in font

### ISSUE THREAD

**Issue by flutterkage2k** [InvoiceShelf/InvoiceShelf#180]
I use Korean and Japanese. 

PDF is generated and error occurs in font, please check the screenshot.
Please let me know if you have any solution regarding PDF font change.

![pdf_error](https://github.com/user-attachments/assets/1945f5fe-ffdc-482c-bd04-79ba010826da)

**Screenshots**
http://naver.me/xWTxwKEv

**Comment by lalapo420** [comment]
1. Download a CJK font like Noto CJK
2. Download "load_font.php" from here https://github.com/dompdf/utils
3. Upload both file to: /vendor/dompdf/dompdf
4. SSH to /vendor/dompdf/dompdf
5. Run:
php load_font.php notocjk notocjk.ttf

6. Open /vendor/dompdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php
Add:
’notocjk’ =>
            [
                'normal' => $distFontDir . '/notocjk',
                'bold' => $distFontDir . '/notocjk',
                'italic' => $distFontDir . '/notocjk',
                'bold_italic' => $distFontDir . '/notocjk'
            ]

7. Open /config/dompdf.php
Change line 79 to true:
"enable_font_subsetting" => true,

8. template dir: /resources/views/app/pdf/
Change or duplicate template you need in all dir
font-family: "notocjk";

9. Template img dir: /public/build/img/PDF
Add image if you duplicated template

**Comment by flutterkage2k** [comment]
> 6. Open /vendor/dompdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php
>    Add:
>    ’notocjk’ =>
>    [
>    'normal' => $distFontDir . '/notocjk',
>    'bold' => $distFontDir . '/notocjk',
>    'italic' => $distFontDir . '/notocjk',
>    'bold_italic' => $distFontDir . '/notocjk'
>    ]


Thanks a lot. 
But,my case No6 **"dompdf_font_famliy_cache.dist.php"** file does not exist.
I applied the font family to except No6 for the file. 

But CJK font is not applied.

**Comment by lalapo420** [comment]
maybe my wrong spelling?
the file should be: dompdf_font_family_cache.dist.php

**Comment by flutterkage2k** [comment]
> maybe my wrong spelling? the file should be: dompdf_font_family_cache.dist.php

no. the file does not exist .
![CleanShot 2024-10-12 at 13 40 51@2x](https://github.com/user-attachments/assets/7792e5d4-03a3-4aa4-87aa-141147bb9105)

**Comment by lalapo420** [comment]
[dompdf_font_family_cache.zip](https://github.com/user-attachments/files/17348842/dompdf_font_family_cache.zip)

**Comment by flutterkage2k** [comment]
> [dompdf_font_family_cache.zip](https://github.com/user-attachments/files/17348842/dompdf_font_family_cache.zip)

Wow!! I will do it soon.

**Comment by rihards-simanovics** [comment]
@lalapo420 for security reasons please share code snippets using Markdown with codeblock like below, and not with zip files.

Reason for that is security of our community, as zip files are the most common ways to spread malicious files. I will allow on this occasion but going forward I will remove links with zip files attached to a comment.

file.php
```php
echo "Hello World";
```

<pre>
file.php
```php
echo "Hello World";
```
</pre>

**Comment by flutterkage2k** [comment]
> [dompdf_font_family_cache.zip](https://github.com/user-attachments/files/17348842/dompdf_font_family_cache.zip)

.... still.. same issue. 

I will update you if there are any changes.

**Comment by lalapo420** [comment]
i just migration crater to invoiceSheif to test,
does all the step and no luck,
then copy font file to this dir manualy: /vendor/dompdf/dompdf/lib/fonts/
and add font name in this file  : /vendor/dompdf/dompdf/lib/fonts/installed-fonts.dist.json
test ok, asian fonts work fine

**Comment by flutterkage2k** [comment]
I solved it as follows. 
1. I put the cjk font in the connected volumes font. 
2. vimeditor all report pdf 

```
body {
            font-family: "notosanskr";
            src: url('/data/fonts/NotoSansKR-Black.ttf')
        } 

``` 
I have changed and added the contents.
![CleanShot 2024-10-13 at 11 49 05@2x](https://github.com/user-attachments/assets/b6163749-520f-4391-a340-fc67a4540b56)

**Comment by gdarko** [comment]
I will reopen the issue, we need to find a workaround for this.

**Comment by rihards-simanovics** [comment]
> I will reopen the issue, we need to find a workaround for this.
> 
> An idea: reconfigure DOMPDF to use CJK font if the app language is any of those: Chinese,Japanese,Korean.

Might not be necessary, the fonts can be chained so if a character is missing in one the fallback font will be used. Here is how it could be achieved:

```css
body {
  font-family: "Primary Font", "Fallback Font 1", "Fallback Font 2", sans-serif;
}
```

Email clients use that a lot.

**Comment by rihards-simanovics** [comment]
linked to #252

**Comment by rihards-simanovics** [comment]
Issue now tracked in https://github.com/InvoiceShelf/InvoiceShelf/issues/438. Closing to reduce number of old issues.
