### ISSUE TITLE
Customer names display Issue: Incorrect names shown when filtering invoices in v2

### ISSUE THREAD

**Issue by jmsx** [InvoiceShelf/InvoiceShelf#181]
**Describe the bug**
When filtering or selecting customers, incorrect names are displayed. For example, when entering an invoice, the correct customer name is shown, but when filtering the list of invoices, it doesn't update correctly until navigating between pages. This issue has been occurring since upgrading to version 2.

**Expected behavior**

Customer names should be displayed correctly when filtering or selecting.
The list of invoices should update immediately and accurately when applying filters, without requiring navigation between pages.

**Screenshots**

![Captura de pantalla 2024-10-08 134611](https://github.com/user-attachments/assets/4e4b2856-d827-4be9-b166-60dc767fe545)
![Captura de pantalla 2024-10-08 134816](https://github.com/user-attachments/assets/cb86d7b4-3630-4778-99a5-39bac1364ea2)

InvoiceShelf version: 2
PHP version: 8.2.23

System Information:

OS: Linux fr-int-web1652.main-hosting.eu 5.14.0-427.33.1.el9_4.x86_64
Build Date: Aug 28 2024
Build System: Linux buildfarm08-new.corp.cloudlinux.com 4.18.0-553.8.1.el8_10.x86_64

Optional info
Browser: Chrome

**Comment by Honigbrot** [comment]
+1 this also happens when using pagination to display e.g. the 2nd page of invoices

**Comment by Pazekal90** [comment]
When an we expect those fixes to go into a new version? At the moment i have to sent all my invoices by hand becuase the 2.0.0 version has so many issues. Is there a workaround in the meantime?

**Comment by gdarko** [comment]
> When an we expect those fixes to go into a new version? At the moment i have to sent all my invoices by hand becuase the 2.0.0 version has so many issues. Is there a workaround in the meantime?

Hey @Pazekal90  

We are aiming to release v2.1 in the coming week, hopefully by 11th Nov.

**Comment by BaxAndrei** [comment]
I am not sure but I saw this issue when navigating pages too (for expense, customers, invoice etc)

**Comment by Honigbrot** [comment]
> > When an we expect those fixes to go into a new version? At the moment i have to sent all my invoices by hand becuase the 2.0.0 version has so many issues. Is there a workaround in the meantime?
> 
> 
> 
> Hey @Pazekal90  
> 
> 
> 
> We are aiming to release v2.1 in the coming week, hopefully by 11th Nov.

Any ETA for v2.1 or should we merge the fix?
