### ISSUE TITLE
Need a nice template for invoice and co.

### ISSUE THREAD

**Issue by approde** [InvoiceShelf/InvoiceShelf#182]
I need a template with a nice footer. Has anyone already adapted the templates to a good-looking invoice?

**Comment by rihards-simanovics** [comment]
Invalid, GitHub Issues are for bugs and feature requests, not for questions about the software, for that I welcome you to join our Discord Server, here is the link: https://discord.gg/hwg2FtwWHW

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
