### ISSUE TITLE
Unable to install project

### ISSUE THREAD

**Issue by harrowmykel** [InvoiceShelf/InvoiceShelf#202]
**Describe the bug**
After you clone the project and try to install it. You are unable to use the /installation url to complete the installation. It hangs at the database configuration part

**Expected behavior**
installation should be completable

**Screenshots**

**Please complete the following information:**
- InvoiceShelf version: 2.0.0
- PHP version: 8.2.12 
- Database type and version: mariadb 10.4, sqlite3

**Optional info**
- OS: windows
- Browser: chrome

**Comment by AliMughal169** [comment]
does it give any kind of error message or did you inspect? are you using docker or herd?

**Comment by harrowmykel** [comment]
I am running the code directly via apache2 and mysql. 

I think the code breaks because during installation the XCSRF Token in the cookie expires.


You can reproduce this by

- Download the current version
- Create empty DB
- go to url, and type in your db config
- try to complete the installation

**Comment by rihards-simanovics** [comment]
> I am running the code directly via apache2 and mysql.
> 
> I think the code breaks because during installation the XCSRF Token in the cookie expires.
> 
> You can reproduce this by
> 
> * Download the current version
> * Create empty DB
> * go to url, and type in your db config
> * try to complete the installation

I am unable to recreate the issue with a standard LEMP stack. Can you please check your Apache config as it could be interfering with correct operation of the app? Also, can you also monitor the `console` and `network` tab for any errors from server responses, and paste those responses/errors/warnings/logs etc in a screenshot or a markdown `log` code block format here so I can further assist you?

**Comment by rihards-simanovics** [comment]
Closing as unable to re-produce.
