### ISSUE TITLE
Add extension whitelist to company logo file name

### ISSUE THREAD

**Issue by gdarko** [InvoiceShelf/InvoiceShelf#21]
**Describe the bug**
This is security bug reported previously.

**Expected behavior**
Correctly validate company profile photo.

**Old pull request**
https://github.com/crater-invoice/crater/pull/1271

**Original issue**
https://github.com/crater-invoice/crater/issues/1267

**Comment by nielsdrost7** [comment]
Related Crater issue: https://github.com/crater-invoice/crater/issues/1267

**Comment by gdarko** [comment]
I was not fan of the [asylumdx](https://github.com/asylumdx)'s implementation but it served as a good example. Kudos! 

This security issue also affects other upload locations, not only company logo.

The [fix](https://github.com/InvoiceShelf/InvoiceShelf/commit/8918ea51241f813601685428fc1f1c041a1e7ae1) properly validates the data in the `Base64Mime.php` file.
