### ISSUE TITLE
Add support for signatures/stamps and authors

### ISSUE THREAD

**Issue by dkorecko** [InvoiceShelf/InvoiceShelf#236]
### What feature or improvement do you think would benefit InvoiceShelf?

Some countries (for example Slovakia) require a stamp and a signature to be provided on each invoice, as well as the name of the author of said invoice. This is one of only a few missing features I'm missing before I can fully adopt InvoiceShelf into my workflow.

### Requirements

- Ability to sign an invoice with full name (could be derived from the user account).
- Add support for adding a signature image (which can be either an actual signature, a stamp or a combination of both) to the user account.

### App Version

v2.0.0

**Comment by rihards-simanovics** [comment]
I know this is a not a full solution atm, but you could embed the signature and other data directly in the invoice template.

**Comment by dkorecko** [comment]
> I know this is a not a full solution atm, but you could embed the signature and other data directly in the invoice template.

Thanks for the suggestion regardless, that could work

**Comment by rihards-simanovics** [comment]
linked to #252
