### ISSUE TITLE
Add payment details to invoice and personalization

### ISSUE THREAD

**Issue by dkorecko** [InvoiceShelf/InvoiceShelf#238]
### What feature or improvement do you think would benefit InvoiceShelf?

In some countries (such as Slovakia), it's mandatory to include payment details on an invoice. This would mean the bank account, SWIFT code, IBAN and other details. It would be great if this could be supported and even customizable in the settings via the personalization tab. 

### Requirements

- When adding a company, I should be able to specify payment details for my invoices
- Payment details should be formatted based on what I set it as on my personalization tab
- Should be placed on the actual invoices when filled out

### App Version

v2.0.0

**Comment by rihards-simanovics** [comment]
linked to #252

**Comment by Robubble** [comment]
As a workaround you could add it as an invoice note: 
Settings/Notes/Add Note with Type set to invoice
And then select this note in the invoice.

Visually not a 100% appealing but it does the job for me until I understand how to make my own templates or html templates arrive (whatever happens first 😄)
