### ISSUE TITLE
Discord Link not working

### ISSUE THREAD

**Issue by acobrerosf** [InvoiceShelf/InvoiceShelf#24]
I tried to joined to discord using the link on the README.md but seems to be invalid.

**Comment by gdarko** [comment]
Hey @acobrerosf  - Thanks for reporting the issue. 

I noticed that i shared temporary link which expired. 

I corrected that now.

Best,
Darko

**Comment by vliubko** [comment]
Fixed in https://github.com/InvoiceShelf/InvoiceShelf/commit/acf3ca2c2649c03d094f1ebc0d77500218ffbc8d
