### ISSUE TITLE
Recurring Invoice Functionality (based on number of days)

### ISSUE THREAD

**Issue by dzeto** [InvoiceShelf/InvoiceShelf#242]
### What feature or improvement do you think would benefit InvoiceShelf?

Hi team,

First off, I want to commend you on this excellent project! It's truly impressive. I would like to suggest a feature to enhance the functionality: support for recurring invoices. This functionality would allow users to send recurring invoices automatically based on the issue date of the last invoice. This would really help to many business cases.

### Requirements

**Example Scenario:**
An invoice is issued on 06.12.2024, with a payment term of 1 month (30 days).
The system should automatically generate and send a new invoice on 06.01.2025 (1 month after the issue date).

**Flexibility in Term Selection:**
- Allow users to specify the recurring term length (value in number of days should be perfect and simple).
- Provide an option to send the new invoice a certain number of days before the recurrence date. For instance, for yearly invoices, the system could notify/send the invoice 30 days before the due date.

**Technical Suggestion:**
Implement a single cron job that runs once every 24 hours.

This cron job would:
- Check each invoice's issue date and its associated recurring term.
- Determine if a new recurring invoice needs to be generated.
- Generate and automatically send the invoice if needed.

**Benefits:**
Streamlined invoice management for businesses with recurring payments.
Enhanced user experience with flexible scheduling options.

Thank you for considering this feature request. I’m confident this will make InvoiceShelf even more powerful and user-friendly!

Let me know if further clarification is needed.

Best regards,
Anže

### App Version

v2.0.0

**Comment by rihards-simanovics** [comment]
@dzeto you already can create [recurring invoices](https://docs.invoiceshelf.com/guide/recurring-invoices.html). Although there is no option right now to run it after every `X` number of days like say every 5 or 8 days, though you can make it run based on:
- Every Minute
- Every 30 Minute
- Every Hour
- Every 2 Hour
- Every day at midnight
- Every Week
- Every 15 days at midnight
- On the first day of every month at 00:00
- Every 6 Month
- Every year on the first day of january at 00:00
- Custom (cron format)

I will close this issue for now as this requests feature that already technically exists. That said if you are looking to add any specific enhancement to the Recurring invoices feel free to re-open this issue.
