### ISSUE TITLE
Forms fuctionality/estimate requests

### ISSUE THREAD

**Issue by neliets** [InvoiceShelf/InvoiceShelf#243]
### What feature or improvement do you think would benefit InvoiceShelf?

For example, I am setting up Invoiceshelf for my self-employed father.
Currently we have a contact/price request form on Youforms, and that then sends an email, plus a webhook to my n8n server that then creates the customer if it does not exist.

I think it would benefit the end user if this sort of functionality was part of Inoviceshelf. This functionality is very important for one-time customers.

### Requirements

- Public Form Link for new estimates
- Email notification for said requests
- Status for these requests (new, processed etc)
- Create customer(if doesnt exist) and fill out some entries in estimate on "Process The Request" action.

### App Version

v2

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
