### ISSUE TITLE
Revisit Installer (Phase 1)

### ISSUE THREAD

**Issue by gdarko** [InvoiceShelf/InvoiceShelf#26]
**Describe the bug**
There are multiple issues reported by people, i was able to reproduce most of them:

1. Duplicating cookies, causes the request to be denied by the webserver. (Try refreshing the installer page and watch the cookies)
2. CSRF issues on domain set step
3. Unable to use installer while using "yarn dev". It only works when the app is pre-built using "yarn build" (not a problem for compiled release versions downloaded through the website, github releases or via docker, but annoying when using "yarn dev" as developer)
4. There is weird "database_created" flag which sometimes causes the user to be redirected to the installation pages even if the database is installed.

**Expected behavior**
Installer is consistent in all use-cases and works as expected.

**Please complete the following information:**
- InvoiceShelf version: 1.0.0
- PHP version: 8.2.0
- Database type and version: MySQL 8 / MariaDB 10 / MariaDB 11

**Optional info**
- OS:  Ubuntu
- Browser: Chromium

**Comment by agencetwogether** [comment]
Good idea 

Installer is very weird. 
And honestly I had always issues with it.

**Comment by nielsdrost7** [comment]
Additionally to above bugs:

1. During install the installer just `hangs` and returns an error.
2. Check the `SetupController` for that specific function
3. Increase timeout for installing/migration/seeding (?)
4. Send that migration to a special background job (?) Problem with that is that you then need a worker... and then you need to adjust the Docker setup
5. Use database transactions to migrate (?), that way you can rollback and then you don't have 1/2 install

**Comment by gdarko** [comment]
Thanks @nielsdrost7 -

I will keep testing the installer  and work on the suggestions you mentioned in #30
