### ISSUE TITLE
Question - Modify or Add new PDF Templates

### ISSUE THREAD

**Issue by Hoschi1982** [InvoiceShelf/InvoiceShelf#31]
Hy there,

Is it possible to modify existing PDF templates or add a new without create new image?

Thanks in advance
Kaputschino

**Comment by gdarko** [comment]
Hey @Hoschi1982 ,

To remove the default logo  from the invoices, set a logo for your company profile.

Not possible to adjust the templates right now unless you edit those in [pdf dir] directly (https://github.com/InvoiceShelf/InvoiceShelf/tree/master/resources/views/app/pdf), but bear in mind that those can get overwritten if you update the app later.

Best Regards,
Darko

**Comment by Hoschi1982** [comment]
Thanks for the quick reply.

I created my own templates in crater invoice. Unfortunately, this is currently not possible without creating your own docker image. When an updated image is deployed, effort is required. It would be great if templates could also be contributed via a mapped volume.

thanks a lot :)

**Comment by gdarko** [comment]
> Thanks for the quick reply.
> 
> I created my own templates in crater invoice. Unfortunately, this is currently not possible without creating your own docker image. When an updated image is deployed, effort is required. It would be great if templates could also be contributed via a mapped volume.
> 
> thanks a lot :)

Hey @Hoschi1982 

The volume is a good idea. I will take a look asap.

Can you please briefly explain how exactly you did it before with crater?

Thanks.

**Comment by Hoschi1982** [comment]
Hello. Thank you for your quick reply.

To create a new template, I created a new blade file on the path "resources/views/app/pdf/invoice" (for Invoices) and "resources/views/app/pdf/estimate" (For Estimates) and "resources/views/app/pdf/payment" (For Payments)

In Crater, the local directory was used, which is why I was able to create the files directly there.

Is the information enough?

thank in advance

**Comment by FreneticScribbler** [comment]
Mounting the contents of my old Crater 'resources/views/app/pdf' to container path '/var/www/html/InvoiceShelf/resources/views/app/pdf' is a quick and dirty fix to get custom templates working again. I know it's not ideal (as now I'm stuck to that copy of the templates, ignoring anything from your repo), but it got me working again.

BTW. Thanks for picking up this project :+1:

**Comment by guyke01** [comment]
Got the same vite manifest error when creating a new template. The .png file is in the folder mentoined by the error.

![Screenshot_1](https://github.com/user-attachments/assets/3e24eda2-8e80-48dc-a4d1-933466fcf882)

**Comment by mchev** [comment]
> Got the same vite manifest error when creating a new template. The .png file is in the folder mentoined by the error.

Hi, did you run `yarn build` or `npm run build` again after the modifications ?

**Comment by guyke01** [comment]
Hi @mchev, i'm running the docker version of InvoiceShelf. Do i need to install npm in the container and run it from a path?

**Comment by mchev** [comment]
I'm not sure with docker, i see that the DockerFile is running 'yarn build' so i guess you just have to rebuild the image.

**Comment by guyke01** [comment]
I did not managed to fix it with building. For now i've copied the files to the public/build/assets folder and added a rule in the manifest.json.

**Comment by gdarko** [comment]
I will look in to the Docker setup and see if we can allow the templates to be modified via mapped volume.

**Comment by leonidas-o** [comment]
@gdarko Yeah, me too. I also have some custom files in dirs like `resources/views/app/pdf/estimate/` or `resources/views/app/pdf/invoice/`, my own `my-custom-inv.blade.php`, as well as in `partials` dir. 
We would definitely need a way to customise that, a volume mount should work. Pre-seeded with the data from the container, we just throw our custom files in there. That should be it.

**Comment by leonidas-o** [comment]
The Vice manifest issue could be solved by
1. enter the docker container
2. add your own images to `resources/static/img/PDF/` and `public/build/assets/` 
3. add the references to `public/build/manifest.json` like:
```json
  "resources/static/img/PDF/my-image-est.png": {
    "file": "assets/my-image-est.png",
    "src": "resources/static/img/PDF/my-image-est.png"
  },
```
4. restart php fpm service
```bash
/etc/init.d/php8.2-fpm restart
```

**Comment by krombel** [comment]
Thanks @leonidas-o for your hint with the manifest file. (btw restart of php-fpm should not be required)

I had a look into that topic and want to note my findings.
1. invoiceTemplates() [tries to resolve the asset path by `Vite::asset`](https://github.com/InvoiceShelf/InvoiceShelf/blob/2.0.0/app/Models/Invoice.php#L673-L685) - which does a lookup through the manifest.json [asset()](https://github.com/laravel/framework/blob/v11.9.2/src/Illuminate/Foundation/Vite.php#L665-L676) and [chunk()](https://github.com/laravel/framework/blob/v11.9.2/src/Illuminate/Foundation/Vite.php#L778-L785) - where the observed error comes from. So this error mainly comes from the file not beeing in the manifest.json
2. The manifest.json is "normally" created by `vite build` during build. Especially for the docker container, where node is not installed, this is not possible to be run. So we could tamper with the manifest.json through json-parsing and updating it with `make:template` . But this does not work reliably as the file is updated by the build process on every rebuild/update of InvoiceShelf so not really a solution.

I think it would be best to
1. just "default" to invoice1/estimate1 in case that file is not found
2. Create a "dedicated" template/image directory for custom invoices/estimates which can then referred to in invoiceTemplates() which in turn makes in accessible by the "normal rendering".

Do I miss something? I don't know the code base nor laravel nor vite so I might oversee something but this is my first impression. I hope it helps fixing it (long term)

**Comment by rihards-simanovics** [comment]
Closing as stale, also for future questions please utilise the [discussions (Q-A)](https://github.com/InvoiceShelf/InvoiceShelf/discussions/categories/q-a)

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
