### ISSUE TITLE
Using https leads to an error

### ISSUE THREAD

**Issue by Hoschi1982** [InvoiceShelf/InvoiceShelf#33]
When I use https, I get the following error:

Mixed Content: The page at 'https://{domain}/installation' was loaded over HTTPS, but requested an insecure stylesheet 'http://{domain}/build/assets/main-qvsb96KG.css'. This request has been blocked; the content must be served over HTTPS.

In crater I added the following line in the file 'crater\resources\views\app.blade.php', so it works:

``` html
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```

Is it possible to add it in the image or do you have another idea how to solve the problem?

thanks :)

**Comment by gdarko** [comment]
Hey @Hoschi1982 - Can you test if adding the following to .env helps:

Weird that the build css still loads as http. Will do some more tests and get back to you.

APP_URL=https://... 

Thanks

**Comment by Hoschi1982** [comment]
Hello I made the following adjustment in the docker-compose.yml file:

``` docker
environment:
      - APP_FORCE_HTTPS=true
      - APP_URL=https://{domain}
```

``` bash
docker-compose down
docker-compose up -d
```

Unfortunately I still get the same error.

**Comment by Hoschi1982** [comment]
I've found the solution to the problem.

I'm using nginx as a reverse proxy. A setting must also be made there.

``` bash
location / {
    proxy_pass http://{_____replaceip_____}/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect http:// https://;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Forwarded-Host $server_name;
  }
```
