### ISSUE TITLE
API returns html instead of json on validation errors

### ISSUE THREAD

**Issue by dariuszz123** [InvoiceShelf/InvoiceShelf#39]
**Describe the bug**
When encountering validation errors, the [API](https://api-docs.invoiceshelf.com/) responds with a `200` status code and returns an `HTML` response instead of the expected `JSON` format.
For example: Invalid user credentials is provided for `POST` `/api/v1/auth/login` endpoint:
```json
{
    "username": "invalid@user.com",
    "password": "INVALID_PASSWORD",
    "device_name": "api"
}
```
Response has status code `200` and contains `HTML` instead of `JSON`:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>InvoiceShelf - Self Hosted Invoicing Platform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
    <link rel="manifest" href="/favicons/site.webmanifest">
    <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5851d8">
    <link rel="shortcut icon" href="/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-config" content="/favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <meta name="csrf-token" content="hHHCcPuhFZJK0RhSu08QIq6wRGqiglaCeJTpIe7e">

    <!-- Module Styles -->
    
    <link rel="preload" as="style" href="http://172.18.0.3/build/assets/main-qvsb96KG.css" /><link rel="modulepreload" href="http://172.18.0.3/build/assets/main-gVTYX-GK.js" /><link rel="stylesheet" href="http://172.18.0.3/build/assets/main-qvsb96KG.css" /><script type="module" src="http://172.18.0.3/build/assets/main-gVTYX-GK.js"></script></head>

<body
    class="h-full overflow-hidden bg-gray-100 font-base
     theme-invoiceshelf  ">

    <!-- Module Scripts -->
    
    <script type="module">
                                        
        window.InvoiceShelf.start()
    </script>
</body>

</html>

```

This behavior can be replicated for any validation error when using an API bearer token. For example: missing fields, creating an invoice with a duplicate invoice number, and other similar scenarios.

**Expected behavior**
API endpoint should return error status code `422` (or similar) and contain `JSON` explaining error:
```json
{
    "message": "These credentials do not match our records.",
    "errors": {
        "email": [
            "These credentials do not match our records."
        ]
    }
}
```

**Please complete the following information:**
- InvoiceShelf version: master (same behavior on 1.1.0)
- PHP version: 8.2 (docker)
- Database type and version: maridb:10 (docker)

**Comment by dariuszz123** [comment]
Request header `Accept: application/json` solves this issue.

However the `/api/` endpoints looks a little bit inconsistent: all successful responses is `json` while validation errors result in an `html` response if `Accept: application/json` is missing.

**Comment by rihards-simanovics** [comment]
@mchev when you create a PR for this one, could you add `resolves #39` so the issue is closed when PR merged, thanks.

**Comment by mchev** [comment]
Thank you for your feedback! This is actually expected behavior. When the Accept: application/json header is omitted, the application defaults to returning an HTML response for validation errors. This happens because, without this explicit header, the server doesn’t know that the client is expecting a JSON response.

By specifying Accept: application/json in the request header, you’ll receive a JSON response with a 422 error code when validation fails. This follows standard client-server communication conventions.

Feel free to let me know if this answers your question or if you’re still experiencing any issues!

**Comment by rihards-simanovics** [comment]
re-classifying as wont-fix
