### ISSUE TITLE
Changing default language does not work

### ISSUE THREAD

**Issue by Hoschi1982** [InvoiceShelf/InvoiceShelf#43]
**Describe the bug**
When I change the default language in the preference View nothing happens.
The language is always english

**Expected behavior**
Language should change

**Screenshots**

**Please complete the following information:**
- InvoiceShelf version: 1.1.0

**Optional info**
- OS:  docker

**Comment by digipifini** [comment]
Noticed this myself, but I there seems to still be some work to do adding additional languages.  If you look under /resources/lang/ the only available option is the EN (english) folder.  This will require multiple people working to complete full translations, perhaps a POT module developed using CrowdIn or any other crowdsourced translation tool.

**Comment by Hoschi1982** [comment]
Hy,
Thanks for your fast reply.

Crater has several translations.  Privately I use a self-hosted weblate instance for translation.  Automatic translations can also be carried out here in conjunction with a self-hosted libreTranslate instance.  Idea: The languages ​​should be checked in in Crater... if not, maybe you try selecting different languages ​​in Crater and downloading the corresponding json file for each language?  Then everything doesn't have to be translated again.  There's no rush.  I might as well try it.

**Comment by spoutnikfr** [comment]
Localisation exist there : 
> resources/scripts/locales/en.json
I think the upgrade to Laravel 10 + VueJS 3.4 broke the i18n function and need to be carefully patched.

**Comment by gdarko** [comment]
This is fixed with #46 - Awaiting 1.2.0 release.
