### ISSUE TITLE
Migrate model_type in media missing (upgrade from Crater)

### ISSUE THREAD

**Issue by swiffer** [InvoiceShelf/InvoiceShelf#44]
Migration of model_type in media DB table is missing - should be similar to how this is done in

database/migrations/2024_02_11_075831_update_version_110.php

That way existing media is found.

**Comment by Timo972** [comment]
Isn't this the case for multiple columns? Have a look at ``notifications.notifiable_type``, ``personal_access_tokens.tokenable_type`` & ``email_logs.mailable_type`` for example.

**Comment by gdarko** [comment]
@Timo972 - After upgrading from Spatie's media library v8 to v11, the database structure changed slightly. Need to verify this and add the missing columns.

Do you think there are other tables that are missing columns? I am talking about the native Laravel tables - Not sure if they added  more columns over the time. This has to be checked.

**Comment by Timo972** [comment]
I will read through the upgrade guides of Spatie's media library and Laravel to determine which tables changed.
Besides that I think we have to add migrations similar to the migration ``2024_02_11_075831_update_version_110`` for all ``*_type`` columns - for people upgrading from Crater to InvoiceShelf.

**Comment by Timo972** [comment]
> @Timo972 - After upgrading from Spatie's media library v8 to v11, the database structure changed slightly. Need to verify this and add the missing columns.
> 
> Do you think there are other tables that are missing columns? I am talking about the native Laravel tables - Not sure if they added more columns over the time. This has to be checked.
Looks like the database schema is up to date, there are no missing columns. I've opened PR #58 to address this issue among the other polymorphic relationships from crater.
