### ISSUE TITLE
Files (media) not shown

### ISSUE THREAD

**Issue by swiffer** [InvoiceShelf/InvoiceShelf#45]
**Describe the bug**
Upload a profile picture. Save and Refresh User settings.

**Expected behavior**
Profile picture should be shown.

**Screenshots**
![grafik](https://github.com/InvoiceShelf/InvoiceShelf/assets/2990373/afed2d94-783b-4412-a25a-526836cf22cd)

**Please complete the following information:**
- InvoiceShelf version: 1.1.0
- PHP version: 8.3
- Database type and version: MariaDB 11.0

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]

**Comment by swiffer** [comment]
i had to run `php artisan storage:link` - working fine now - maybe should be added to the migration docs?

**Comment by Hoschi1982** [comment]
Hy ... i have the same issue but in docker container. The uploaded file does exist in the storage folder but the GET returns with errorcode 404.
Do you have an idea what it could be?
