### ISSUE TITLE
Custom fields in the PDF template return error

### ISSUE THREAD

**Issue by NightlandDriver** [InvoiceShelf/InvoiceShelf#50]
**Describe the bug**
Custom fields in the PDF template return error: Attempt to read property on null.
Migrated from Crater and there it was working without Problems.

**Expected behavior**
Custom fields in the PDF template should display the correct value of the field.

**Screenshots**
Screenshot 1: View Invoice PDF
![screenshot_01](https://github.com/InvoiceShelf/InvoiceShelf/assets/69898403/932eca70-d641-4eb3-b180-f3e799be811b)

Screenshot 2: Custom Fields Settings
![screenshot_02](https://github.com/InvoiceShelf/InvoiceShelf/assets/69898403/bda6270c-285a-405c-b804-35a097660e4c)

**Please complete the following information:**
- InvoiceShelf version: 1.1.0
- PHP version: 8.2
- Database type and version: MySQL

**Comment by Timo972** [comment]
Hey @NightlandDriver,
I just tried to reproduce your issue on master branch and it seems to be working fine.
Maybe it is related to your migration from Crater to InvoiceShelf.

**Comment by Timo972** [comment]
In fact if you migrated from Crater to InvoiceShelf it might be a similar issue to #44 which is being resolved by #58

**Comment by azaricstefan** [comment]
@NightlandDriver try with my PR if it fixes your issue.

**Comment by azaricstefan** [comment]
Glad it got fixed 😀

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
