### ISSUE TITLE
Cancellation Invoices

### ISSUE THREAD

**Issue by sebarnd** [InvoiceShelf/InvoiceShelf#53]
**Is your feature request related to a problem? Please describe.**

In Germany, I'm sure in other countries too, you are not allowed to change a issued invoice. I order to do it right you have to issue a cancellation invoice (Stornorechnung) relating to the original invoice. The cancellation invoice contains everything as the original invoice but has:

1. a header saying "Cancellation invoice for invoice No. XYZ"
2. Its own invoice number
3. all quantities are negative as are all sums and the grand total  

**Describe the solution you'd like**
I'd like to have a possibility to add cancellation invoices for invoices already issued. There is already a pull request for that in https://github.com/crater-invoice/crater/pull/1114  but it does some weird calculation to the taxes so that they are subtracted from the sum which doesn't make sense to me at all. As a fist step it would be enough for me to have the possibility to

1. Have a switch to change the type to a cancellation invoice
2. use negative quantities
3. somehow add a relation to a invoice to cancel to the cancellation invoice.

**Describe alternatives you've considered**
at the moment I'm doing cancellation invoices using inkscape...

**Comment by mchev** [comment]
Hi @sebarnd, I have a question regarding the handling of cancellation invoices.

When creating a cancellation invoice with negative values, how do you manage the associated payment? For example, after issuing an original invoice followed by a cancellation invoice (using negative quantities), the system should technically register a payment to close out the invoice.

However, adding a negative payment to reflect the cancellation seems counterintuitive. I noticed in the Crater PR that the concept of credit has been introduced, but it feels like overkill for such a simple case.

Wouldn't it be more straightforward to simply mark the invoice as paid if the total is negative? Is there a reason this approach wouldn't work, or could it be an effective solution?
