### ISSUE TITLE
Duplicate estimate

### ISSUE THREAD

**Issue by scramatte** [InvoiceShelf/InvoiceShelf#61]
Hi,

Can you add duplicate estimate feature?

Many times I need to give an alternative to a customer changing few items or quantity  and it takes me a long time to recreate the estimate from scratch.

Alternatively it would nice or including better to have some historical of estimate modifications

Regards

**Comment by gdarko** [comment]
Hey @scramatte ,

Thanks for the suggestion.

Implemented with #97 

Will be available in v2.0.0.
