### ISSUE TITLE
Version 1.2.0 migration missing

### ISSUE THREAD

**Issue by swiffer** [InvoiceShelf/InvoiceShelf#64]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- InvoiceShelf version: 
- PHP version: 
- Database type and version: 

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]

**Comment by gdarko** [comment]
Hey @swiffer - Thanks for the quick action :-). Will release a hotfix v1.2.1 version shortly.

**Comment by gdarko** [comment]
Hot fix 1.2.1 released. Thanks @swiffer! Really appreciated.

**Comment by swiffer** [comment]
nice, thanks!
