### ISSUE TITLE
The estimate number has already been taken 

### ISSUE THREAD

**Issue by scramatte** [InvoiceShelf/InvoiceShelf#67]
**Describe the bug**
When you try to register a payment I get the error "The estimate number has already been taken " when I try to save.

**Expected behavior**
Payment should be saved

**Please complete the following information:**
- InvoiceShelf version: 1.2.2
- PHP version: 8.1
- Database type and version: MariaDB

**Optional info**
- OS:  Debian 12
- Browser: any
-

**Comment by mchev** [comment]
Do you still have this issue ?

**Comment by rihards-simanovics** [comment]
Hey @scramatte, could you please provide the PHP or Laravel logs? If none are generated on PHP side, it could be a good idea to have a look at the browser's console log and see if there are any errors/warning there, if none still, check the network tab in the Inspect element tool to see if any specific request if failing.

**Comment by rihards-simanovics** [comment]
Closing as stale.
