### ISSUE TITLE
Customer portal

### ISSUE THREAD

**Issue by scramatte** [InvoiceShelf/InvoiceShelf#68]
Hi,

It would be nice to have a customer portal or a way to share invoice / quote securely.
Various companies I know suffered an attack/hack that intercept PDF invoices and change bank account number into PDF files

Regards

**Comment by merzainc** [comment]
The original crater codebase used to support this feature

**Comment by gdarko** [comment]
> The original crater codebase used to support this feature

Will verify this and follow up. Nothing is dropped from the original version related to this.

**Comment by mchev** [comment]
There is a Customer Portal  : https://your.url/{company:slug}/customer

You have to edit the customer and give him a portal access (on the edit page).

Actually there is an issue that prevent from accessing to the customer dashboard. It will be fixed in v2.0 (#109)

**Comment by gdarko** [comment]
Hey @scramatte - This is working fine. Thanks @mchev.

![image](https://github.com/user-attachments/assets/5105ddef-d807-4399-a545-b1d20a7169e4)
