### ISSUE TITLE
Not able to write quantities as float

### ISSUE THREAD

**Issue by Marthaarman** [InvoiceShelf/InvoiceShelf#70]
**Describe the bug**
Quantities could be of type float for me. When I'm writing down a quantity in terms of hours that I worked I can round to half hours. 
This is not allowed. (might be a feature request though, but it was possible in Crater before).

**Expected behavior**
I expect both integers and floats to be allowed, not only integers

**Please complete the following information:**
- InvoiceShelf version: 1.2.2
- PHP version: 8.1
- Database type and version: mariadb.10

**Optional info**
- Browser: firefox

**Screenshots**
![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/9247891/bbebb021-966c-49ab-96a2-95fe8c4ff94c)

**Comment by luketanti** [comment]
Same issue here too. This was working fine in the old Crater version
