### ISSUE TITLE
Allow links in notes

### ISSUE THREAD

**Issue by Marthaarman** [InvoiceShelf/InvoiceShelf#71]
**Is your feature request related to a problem? Please describe.**
I'm writing my invoices with a link for quick payment. However, links are not an option in notes.
<a href=''></a> is filtered and not working in the creation of PDF. 

**Describe the solution you'd like**
A button to insert a link and/or allow <a href=''></a> elements

![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/9247891/a4613373-96d7-4173-afec-2336d4ab0ea6)

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
