### ISSUE TITLE
Add Footer (with Tax-ID)

### ISSUE THREAD

**Issue by fabianober** [InvoiceShelf/InvoiceShelf#72]
With release 1.2, we got the ability to add the Tax ID to our company, but currently, there is no way of displaying this ID on an invoice for example.

It would be great to have something like a "general footer" on all PDFs with some company details etc., including the Tax-ID.

**Comment by jmsx** [comment]
@fabianober You can do it through a custom field, I use it this way for the Spanish VAT number. I hope it will help you

**Comment by atik55555** [comment]
is someone working on this issue ? or can i start resolving it ?

**Comment by mchev** [comment]
Should by fixed by #138

**Comment by rihards-simanovics** [comment]
Closing as completed by: https://github.com/InvoiceShelf/InvoiceShelf/pull/138

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
