### ISSUE TITLE
Integer Values Only in Item Quantities

### ISSUE THREAD

**Issue by Bipedal** [InvoiceShelf/InvoiceShelf#80]
**Describe the bug**
When entering non-integers in item quantities, the amount is correctly calculated, but trying to save the invoice results in "Error: The items.0.quantity must be an integer."

**Expected behavior**
e.g. 1.5 hours x €10.00 should result in a €15.00 amount (this currently happens) and be saveable as an invoice.

**Screenshots**
![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/7750652/cfc6a6da-f7e8-4a37-b9f9-98ba618e7d37)

**Please complete the following information:**
- InvoiceShelf version: 1.2.2
- PHP version: 8.2.18
- Database type and version: mariadb:10

**Optional info**
- OS:  Debian 12 (Docker Compose)
- Browser: Firefox, Chrome

**Comment by gdarko** [comment]
Hey @bipedal,

This change will be available as of the next version v2.0.0. 

Thanks for reporting.
