### ISSUE TITLE
Table Item Truncation

### ISSUE THREAD

**Issue by Bipedal** [InvoiceShelf/InvoiceShelf#88]
**Describe the bug**
Long text, particularly the "Customer" field, truncate at 30 characters on the Customers/Estimates/Invoices etc. pages, even if there is more space to display them.

**Expected behavior**
The tables should use the available width to show information

**Screenshots**

![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/7750652/06388647-8452-44aa-a07a-cb74f829e45a)

**Please complete the following information:**
- InvoiceShelf version: 1.2.2
- PHP version: 8.2.18
- Database type and version: mariadb:10

**Optional info**
- OS:  Debian 12 (Docker Compose)
- Browser: Firefox, Chrome

**Comment by gdarko** [comment]
Hey @bipedal,

This change will be available as of the next version v2.0.0. 

Thanks for reporting.
