### ISSUE TITLE
Custom Fields not migrating from Crater

### ISSUE THREAD

**Issue by Honigbrot** [InvoiceShelf/InvoiceShelf#89]
When following the migration guide the custom field values don't get migrated because the custom_field_valuable_type column in the custom_field_values table is named e.g. "Crater\Models\Customer". 

Renaming the entries to e.g. "InvoiceShelf\Models\Customer" fixes the problem.

Maybe a migration with DB::raw replace could fix this in the Crater -> InvoiceShelf Migration process?

<img width="256" alt="image" src="https://github.com/InvoiceShelf/InvoiceShelf/assets/34781745/af1f5d2d-2dc2-42bc-869a-f793977fb7cf">

**Comment by Honigbrot** [comment]
` DB::table('custom_field_values')->update([
            'custom_field_valuable_type' => DB::raw("REPLACE(custom_field_valuable_type, 'Crater', 'InvoiceShelf')")
        ]);`
        
Running this migration fixed it for me

**Comment by enoversum** [comment]
> ` DB::table('custom_field_values')->update([ 'custom_field_valuable_type' => DB::raw("REPLACE(custom_field_valuable_type, 'Crater', 'InvoiceShelf')") ]);`
> 
> Running this migration fixed it for me

Having the same issue, so my templates break by opening an invoice in the backend. May I kindly ask how and where to proceed your proposed migration? It doesn't look like an SQL command?

**Comment by Honigbrot** [comment]
Absolutely!
I just made a new migration by running `php artisan make:migration update_custom_field_valuable_type`

and then edited the newly created migration file to include the above command:
` public function up(): void
    {
        DB::table('custom_field_values')->update([
            'custom_field_valuable_type' => DB::raw("REPLACE(custom_field_valuable_type, 'Crater', 'InvoiceShelf')")
        ]);
    }`
    and
    `
    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('custom_field_values')->update([
            'custom_field_valuable_type' => DB::raw("REPLACE(custom_field_valuable_type, 'InvoiceShelf', 'Crater')")
        ]);
    }`

**Comment by enoversum** [comment]
Danke, Honigbrot, that's certainly very helpful. 
Since more trouble came up after my migration, this time with some storage files, I simply reverted and switched back to my trusty-but-outdated Crater installation, so I can't check your trick at the moment. I'd hope a future update will incorporate this custom field migration step.

**Comment by enoversum** [comment]
@Honigbrot Am I right to conclude that this is going to go into the next release version of InvoiceShelf?

**Comment by Honigbrot** [comment]
This I can't tell since I'm not a maintainer of this project. I just closed this issue because there is another issue and actually an open pull request with this fix, so I'm guessing this migration will be merged into master yes.

**Comment by enoversum** [comment]
@Honigbrot Ah, I see, I just saw the 2.0.0 tag for this issue, I believe. And you have been mentioned on other commits as well :) .
