### ISSUE TITLE
Clean and refactor Github branches

### ISSUE THREAD

**Issue by mchev** [InvoiceShelf/InvoiceShelf#95]
Given that the app will soon have a v2, this would be an opportunity to remove all branches that are no longer needed and keep only two branches: `1.x` and `2.x`, with `2.x` as the base branch.

This would greatly facilitate contributions, which can currently be unclear between `master` and `develop`.

This is how the Laravel repo works, and it allows security updates to be made to v1 if some users wish to continue using it for a while.

**Comment by gdarko** [comment]
We are going to keep master and develop.

- master - The approved code that is merged or released
- develop - The alpha code that is not merged or released but in current development
- X.x - Created whenever we releasing a new major version. Those branches will be used for patching like X.x.1, X.x.2, etc.
