### ISSUE TITLE
Make Send invoice subject translatable

### ISSUE THREAD

**Issue by Honigbrot** [InvoiceShelf/InvoiceShelf#99]
Right now if you send an invoice (and i guess automatic sending of recurring invoices?) the subject defaults to "New invoice". It would be awesome if the default subject would translated or even better customizable in the settings.

**Comment by gdarko** [comment]
For a note:

Looks like @Honigbrot did some work on this on his fork but he still hardcoded those in german.

https://github.com/InvoiceShelf/InvoiceShelf/compare/master...Honigbrot:InvoiceShelf:master

**Comment by Honigbrot** [comment]
oh oops i meant to change this only on my personal fork / branch

**Comment by gdarko** [comment]
Hey @Honigbrot  - No worries, we will make the necessary changes to the upstream InvoiceShelf.

**Comment by gdarko** [comment]
@Honigbrot  - Closing this now as it has been merged into 2.0 (develop) branch.
